"""Tests for harmony/progression_foundations.py — the C/G/F beginner lesson.

Covers the guided collection's contract: exactly 12 deterministic examples,
engine-derived chords matching the acceptance tables, genuine tetrads in the
seventh group, a chord table that mirrors the compiled trainer targets (no
hand-authored theory drift), well-formed annotated MusicXML, honest Atlas
refs, curriculum integration, serialization round-trips, and the Harmonic
Network projection seam.
"""

import json
import os
import sys
import unittest
import xml.etree.ElementTree as ET

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from harmony.progression_foundations import (   # noqa: E402
    FAMILIES,
    FOUNDATION_KEYS,
    FoundationExample,
    SCHEMA_VERSION,
    build_foundations_payload,
    chord_table,
    curriculum_node_id,
    exercise_spec_for,
    foundation_examples,
    lab_spec_for,
    new_foundation_exercise_specs,
    wrap_drill,
)
from harmony.exercise_spec import (             # noqa: E402
    MAX_CHORDS_PER_SPEC,
    compile_exercise,
)
from harmony.musicxml_builder import build_exercise  # noqa: E402


#: The acceptance tables from the lesson spec (assertions only — production
#: values are generated by the theory engine).
EXPECTED_CHORDS = {
    ("full_key_major", "C"): ["C", "Dm", "Em", "F", "G", "Am", "B°"],
    ("full_key_major", "G"): ["G", "Am", "Bm", "C", "D", "Em", "F#°"],
    ("full_key_major", "F"): ["F", "Gm", "Am", "Bb", "C", "Dm", "E°"],
    ("I_IV_V_I", "C"): ["C", "F", "G", "C"],
    ("I_IV_V_I", "G"): ["G", "C", "D", "G"],
    ("I_IV_V_I", "F"): ["F", "Bb", "C", "F"],
    ("ii_V_I", "C"): ["Dm", "G", "C"],
    ("ii_V_I", "G"): ["Am", "D", "G"],
    ("ii_V_I", "F"): ["Gm", "C", "F"],
    ("ii7_V7_I", "C"): ["Dm7", "G7", "C"],
    ("ii7_V7_I", "G"): ["Am7", "D7", "G"],
    ("ii7_V7_I", "F"): ["Gm7", "C7", "F"],
}

EXPECTED_SCALES = {
    "C": ["C", "D", "E", "F", "G", "A", "B"],
    "G": ["G", "A", "B", "C", "D", "E", "F#"],
    "F": ["F", "G", "A", "Bb", "C", "D", "E"],
}


class TestCollection(unittest.TestCase):
    def setUp(self):
        self.examples = foundation_examples()

    def test_exactly_twelve_examples_in_four_groups(self):
        self.assertEqual(len(self.examples), 12)
        self.assertEqual(len(FAMILIES), 4)
        for fam in FAMILIES:
            members = [e for e in self.examples if e.family_id == fam.family_id]
            self.assertEqual(len(members), 3, fam.family_id)
            self.assertEqual([e.key for e in members], list(FOUNDATION_KEYS))

    def test_ids_unique_and_deterministic(self):
        ids = [e.example_id for e in self.examples]
        self.assertEqual(len(ids), len(set(ids)))
        again = foundation_examples()
        self.assertEqual([e.to_dict() for e in self.examples],
                         [e.to_dict() for e in again])
        # exercise ids are unique too (reused ones point at distinct drills)
        ex_ids = [exercise_spec_for(e).exercise_id for e in self.examples]
        self.assertEqual(len(ex_ids), len(set(ex_ids)))

    def test_every_example_validates_within_cap(self):
        for e in self.examples:
            hs = exercise_spec_for(e)
            hs.validate()
            lab = lab_spec_for(e)
            lab.validate()
            self.assertEqual(lab.concept, "drill")
            n = len(compile_exercise(hs))
            self.assertLessEqual(n, MAX_CHORDS_PER_SPEC, e.example_id)

    def test_wrap_drill_matches_curriculum_wrap_native(self):
        from harmony.curriculum import _wrap_native
        for e in self.examples:
            hs = exercise_spec_for(e)
            self.assertEqual(wrap_drill(hs).to_dict(),
                             _wrap_native(hs).to_dict(), e.example_id)

    def test_scales_correctly_spelled(self):
        for e in self.examples:
            compiled = compile_exercise(exercise_spec_for(e))
            for c in compiled.chords:
                self.assertEqual(list(c.triad.scale_pitches),
                                 EXPECTED_SCALES[e.key], e.example_id)

    def test_expected_chord_symbols(self):
        for e in self.examples:
            compiled = compile_exercise(exercise_spec_for(e))
            symbols = [c.triad.chord_symbol for c in compiled.chords]
            self.assertEqual(symbols,
                             EXPECTED_CHORDS[(e.family_id, e.key)],
                             e.example_id)

    def test_seventh_examples_are_genuine_tetrads(self):
        for e in self.examples:
            if e.family_id != "ii7_V7_I":
                continue
            compiled = compile_exercise(exercise_spec_for(e))
            ii7, v7, tonic = [c.triad for c in compiled.chords]
            for tetrad in (ii7, v7):
                self.assertEqual(len(tetrad.pitches), 4, e.example_id)
                self.assertEqual(len(set(tetrad.pitch_classes)), 4)
            self.assertEqual(ii7.chord_quality, "minor_seventh")
            self.assertEqual(v7.chord_quality, "dominant_seventh")
            self.assertEqual(len(tonic.pitches), 3)

    def test_reuse_is_exactly_the_documented_five(self):
        reused = {e.example_id: exercise_spec_for(e).exercise_id
                  for e in self.examples if e.reused}
        self.assertEqual(reused, {
            "foundations_full_key_major_C": "major_fullkey_block_C",
            "foundations_full_key_major_G": "major_fullkey_block_G",
            "foundations_full_key_major_F": "major_fullkey_block_F",
            "foundations_i_iv_v_i_C": "atlas_function_I_IV_V_I_major_C",
            "foundations_ii_v_i_C": "atlas_function_ii_V_I_major_C",
        })
        self.assertEqual(len(new_foundation_exercise_specs()), 7)


class TestChordTable(unittest.TestCase):
    """The table is DERIVED: every row must mirror its compiled target."""

    def test_rows_match_compiled_targets(self):
        from harmony.musicxml_builder import build_trainer_payload
        for e in foundation_examples():
            compiled = compile_exercise(exercise_spec_for(e))
            targets = build_trainer_payload(compiled)["TARGET_CHORDS"]
            rows = chord_table(e)
            self.assertEqual(len(rows), len(targets), e.example_id)
            for row, t in zip(rows, targets):
                self.assertEqual(row["measureNumber"], t["measureNumber"])
                self.assertEqual(row["roman"], t["roman"])
                self.assertEqual(row["chordSymbol"], t["chordSymbol"])
                self.assertEqual(row["chordNotes"], t["chordTones"])
                self.assertEqual(row["pitchClasses"], t["pitchClasses"])
                self.assertEqual(row["quality"], t["quality"])
                self.assertEqual(row["function"], t["functionLabel"])
                self.assertEqual(row["key"], t["key"])
                self.assertEqual(row["scale"], t["scale"])
                self.assertEqual(row["degree"], t["degreeNumber"])

    def test_no_hand_authored_drift(self):
        """Row values equal a fresh engine derivation (nothing hard-coded)."""
        from theory.diatonic_harmony import (
            generate_diatonic_triads, transpose_degree_pattern)
        for e in foundation_examples():
            rows = chord_table(e)
            fam = e.family
            if fam.tokens is None:
                triads = generate_diatonic_triads(e.key, "major")
            else:
                triads = transpose_degree_pattern(
                    list(fam.tokens), e.key, "major")
            self.assertEqual([r["chordSymbol"] for r in rows],
                             [t.chord_symbol for t in triads])
            self.assertEqual([r["chordNotes"] for r in rows],
                             [list(t.pitches) for t in triads])
            self.assertEqual([r["roman"] for r in rows],
                             [t.roman for t in triads])

    def test_display_spellings(self):
        rows_f = chord_table(next(
            e for e in foundation_examples()
            if e.family_id == "full_key_major" and e.key == "F"))
        self.assertEqual(rows_f[3]["chordSymbolDisplay"], "B♭")
        self.assertIn("B♭", rows_f[0]["scaleDisplay"])
        rows_g = chord_table(next(
            e for e in foundation_examples()
            if e.family_id == "full_key_major" and e.key == "G"))
        self.assertEqual(rows_g[6]["chordSymbolDisplay"], "F♯°")

    def test_size_and_gloss_columns(self):
        for e in foundation_examples():
            for row in chord_table(e):
                expected_size = ("seventh chord" if len(row["chordNotes"]) > 3
                                 else "triad")
                self.assertEqual(row["chordSize"], expected_size)
                self.assertTrue(row["functionGloss"], row)
                self.assertTrue(row["relatedLessons"], row)


class TestAtlasHonesty(unittest.TestCase):
    def setUp(self):
        from harmony.atlas import build_atlas
        self.atlas = build_atlas()

    def test_rows_union_matches_curriculum_rule(self):
        """The per-row refs must be the exact per-chord slice of the
        canonical curriculum derivation (no second honesty rule)."""
        from harmony.curriculum import _atlas_refs_for_native
        for e in foundation_examples():
            hs = exercise_spec_for(e)
            union = set()
            for row in chord_table(e):
                union.update(row["atlasNodes"])
            self.assertEqual(union, set(_atlas_refs_for_native(hs)),
                             e.example_id)

    def test_triads_map_to_triad_nodes_sevenths_do_not(self):
        for e in foundation_examples():
            for row in chord_table(e):
                triad_refs = [n for n in row["atlasNodes"]
                              if n.startswith("triad:")]
                if row["chordSize"] == "seventh chord":
                    self.assertEqual(triad_refs, [], row["chordSymbol"])
                    for n in row["atlasNodes"]:
                        self.assertFalse(n.startswith(("quality:", "layer:")),
                                         (row["chordSymbol"], n))
                else:
                    self.assertEqual(len(triad_refs), 1, row["chordSymbol"])

    def test_all_refs_resolve_in_ontology(self):
        for e in foundation_examples():
            for row in chord_table(e):
                for nid in row["atlasNodes"]:
                    self.assertIsNotNone(self.atlas.node(nid),
                                         (e.example_id, nid))

    def test_group_cadence_ids_resolve_where_claimed(self):
        payload = build_foundations_payload()
        by_letter = {g["letter"]: g for g in payload["groups"]}
        for letter in ("B", "C"):
            nid = by_letter[letter]["atlasCadenceId"]
            self.assertIsNotNone(self.atlas.node(nid), nid)
        # no Atlas cadence node exists for the full field or the seventh
        # pattern — the payload must not fabricate one
        self.assertIsNone(by_letter["A"]["atlasCadenceId"])
        self.assertIsNone(by_letter["D"]["atlasCadenceId"])


class TestMusicXML(unittest.TestCase):
    def test_well_formed_one_measure_per_chord_with_annotations(self):
        for e in foundation_examples():
            compiled = compile_exercise(exercise_spec_for(e))
            xml, payload = build_exercise(compiled)
            root = ET.fromstring(xml)                      # raises if malformed
            measures = root.findall(".//measure")
            self.assertEqual(len(measures), len(compiled.chords), e.example_id)
            self.assertEqual(len(measures), len(payload["TARGET_CHORDS"]))
            for m in measures:
                harmonies = m.findall("harmony")
                # chord symbol (above) + Roman numeral (below)
                self.assertEqual(len(harmonies), 2, e.example_id)
                self.assertIsNotNone(m.find("harmony/root/root-step"))
                self.assertIsNotNone(m.find("harmony/numeral/numeral-root"))

    def test_verovio_renders_each_example_on_one_page(self):
        try:
            import verovio
        except Exception as e:  # pragma: no cover
            self.skipTest(f"verovio not available: {e}")
        tk = verovio.toolkit()
        for e in foundation_examples():
            compiled = compile_exercise(exercise_spec_for(e))
            xml, _ = build_exercise(compiled)
            self.assertTrue(tk.loadData(xml),
                            f"verovio failed to load {e.example_id}")
            self.assertEqual(tk.getPageCount(), 1, e.example_id)
            svg = tk.renderToSVG(1)
            self.assertIn("<svg", svg)
            self.assertIn("note", svg)

    def test_key_signatures(self):
        expected_fifths = {"C": 0, "G": 1, "F": -1}
        for e in foundation_examples():
            compiled = compile_exercise(exercise_spec_for(e))
            xml, _ = build_exercise(compiled)
            root = ET.fromstring(xml)
            fifths = root.find(".//measure/attributes/key/fifths")
            self.assertEqual(int(fifths.text), expected_fifths[e.key],
                             e.example_id)


class TestCurriculumIntegration(unittest.TestCase):
    def setUp(self):
        from harmony.curriculum import build_curriculum
        self.root = build_curriculum()
        self.ids = {n.id for n in self.root.walk()}

    def test_bridge_lesson_registered_under_functions(self):
        lesson = self.root.find("lesson:progression_foundations")
        self.assertIsNotNone(lesson)
        self.assertEqual(lesson.parent, "cat:functions")
        # the seven NEW drills live under the lesson; the five reused ones do not
        self.assertEqual(lesson.exercise_count, 7)

    def test_every_example_resolves_to_a_curriculum_leaf(self):
        for e in foundation_examples():
            nid = curriculum_node_id(e)
            node = self.root.find(nid)
            self.assertIsNotNone(node, nid)
            self.assertEqual(node.kind, "exercise", nid)
            # the leaf's lab spec launches the exact same drill
            inner = node.lab_spec.to_exercise_specs()[0]
            self.assertEqual(inner.exercise_id,
                             exercise_spec_for(e).exercise_id, nid)

    def test_lesson_related_references_resolve(self):
        lesson = self.root.find("lesson:progression_foundations")
        self.assertTrue(lesson.related)
        for rid in lesson.related:
            self.assertIn(rid, self.ids, rid)
        # the five curriculum areas are all linked
        for area in ("cat:scales", "cat:chords", "cat:degrees",
                     "cat:functions", "cat:sevenths"):
            reachable = set(lesson.related) | {lesson.parent}
            self.assertIn(area, reachable, area)

    def test_row_related_lessons_resolve(self):
        for e in foundation_examples():
            for row in chord_table(e):
                for rid in row["relatedLessons"]:
                    self.assertIn(rid, self.ids, rid)


class TestSerialization(unittest.TestCase):
    def test_example_round_trip_keeps_family_id(self):
        for e in foundation_examples():
            d = e.to_dict()
            self.assertEqual(d["schema"], SCHEMA_VERSION)
            self.assertEqual(d["familyId"], e.family_id)
            back = FoundationExample.from_dict(json.loads(json.dumps(d)))
            self.assertEqual(back, e)
            self.assertEqual(back.family_id, e.family_id)

    def test_payload_json_serialisable_and_deterministic(self):
        a = build_foundations_payload()
        b = build_foundations_payload()
        self.assertEqual(json.dumps(a, sort_keys=True),
                         json.dumps(b, sort_keys=True))
        self.assertEqual(len(a["groups"]), 4)
        self.assertEqual(sum(len(g["examples"]) for g in a["groups"]), 12)
        for g in a["groups"]:
            for ex in g["examples"]:
                self.assertEqual(ex["familyId"], g["familyId"])
                self.assertTrue(ex["labSpec"]["experiment_id"])
                self.assertEqual(len(ex["table"]),
                                 len(ex["chordSymbols"]))

    def test_lab_spec_dicts_round_trip(self):
        from harmony.lab_spec import LabExperimentSpec
        for g in build_foundations_payload()["groups"]:
            for ex in g["examples"]:
                spec = LabExperimentSpec.from_dict(
                    json.loads(json.dumps(ex["labSpec"])))
                self.assertEqual(spec.concept, "drill")


class TestNetworkProjection(unittest.TestCase):
    """Projection-readiness: every example projects deterministically today."""

    def setUp(self):
        from harmony.harmonic_network import build_network
        from harmony.network_template import get_template
        self.net = build_network(
            get_template("dominant_diminished_relative_network_v1"))

    def test_all_examples_project_and_validate(self):
        from harmony.network_projection import project_harmony_exercise
        for e in foundation_examples():
            spec = exercise_spec_for(e)
            proj = project_harmony_exercise(spec, self.net)
            proj.validate()
            self.assertEqual(len(proj.steps),
                             len(compile_exercise(spec)), e.example_id)
            # ordered occurrences with key context retained
            for step in proj.steps:
                self.assertTrue(step.occurrence_id)
                self.assertIn(e.key, step.key_context)

    def test_v7_exact_on_dom7_node(self):
        from harmony.network_projection import project_harmony_exercise
        dom7_roots = {"C": "G", "G": "D", "F": "C"}
        for e in foundation_examples():
            if e.family_id != "ii7_V7_I":
                continue
            proj = project_harmony_exercise(exercise_spec_for(e), self.net)
            by_roman = {s.roman: s for s in proj.steps}
            self.assertEqual(by_roman["V7"].mapping_status, "exact",
                             e.example_id)
            self.assertEqual(by_roman["V7"].visual_node_id,
                             f"hn:dom7:{dom7_roots[e.key]}")
            # ii7 has no network node on this template: an honest proxy,
            # never a triad masquerade (documented limitation)
            self.assertEqual(by_roman["ii7"].mapping_status, "contextual")
            self.assertTrue(
                by_roman["ii7"].visual_node_id.startswith("overlay:"))


if __name__ == "__main__":
    unittest.main()
