"""Topological templates for the Functional Degree Network.

The **Functional Degree Network** is the practice-first sibling of the
Harmonic Network / Tonal Graph layer (:mod:`harmony.network_template` /
:mod:`harmony.harmonic_network`).  Where the v1 network wires *whole keys*
(major / relative minor / V7 / vii°) together across the full circle of
fifths, this network makes **every diatonic degree of a few journey keys a
real graph node**, grouped by harmonic function (T / PD-S / D), and reveals
itself in guided stages driven by the Harmony Trainer
(:mod:`harmony.functional_journey`).

This module is the **schema** for that layer -- a deliberate *mirror* of
:mod:`harmony.network_template` with its own closed vocabularies.  The v1
vocabularies (``NODE_KINDS`` / ``ALL_RELATIONS``) are NOT widened: their
``validate()`` is a contract other tests rely on, so this module is a
parallel schema, not an extension (see docs/functional_network_plan.md §5).

A :class:`FunctionalNetworkTemplate` is a pure, serialisable description of:

* the node *classes* (diatonic degree triad / function group / key hub);
* the edge *classes* (functional relationship vocabulary: membership,
  resolution, preparation, substitution, deception, cross-key identity),
  split into implemented and reserved relations;
* the layout rules: one **panel per journey key** (panels ordered by fifths)
  with fixed functional positions inside the panel -- the T→PD→D→T cycle the
  eye can follow (PD/S column left, D column right, T cluster bottom-centre);
* which deterministic *generation rules* the builder should run;
* the launch rules (everything here is triad-based, so **every node is
  launchable** -- no reserved drills anywhere in this graph).

It deliberately contains **no theory tables**: the actual nodes/edges are
generated by :mod:`harmony.functional_network` from the live theory engine
(:mod:`theory.diatonic_harmony`).  This template graduates the audited
``core_triad_function_network_v1`` planned stub (and the staged-drill half of
``cadence_resolution_network_v1``) into one concrete, buildable topology.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional

# The dumb node/edge-class records are schema-agnostic; reuse them verbatim
# (all vocabulary validation lives on the template class below, so importing
# them cannot loosen the v1 module's contract).
from harmony.network_template import NodeClass, EdgeClass
# Display labels/badges come from the single function vocabulary (ticket 01 / plan F1); the
# closed schema vocabularies (NODE_KINDS / ALL_RELATIONS / FUNCTION_GROUPS keys) stay frozen.
from harmony.harmonic_roles import INTERNAL_FAMILY_SHORT, internal_family_label


SCHEMA_VERSION = "harmony-functional-network-template/v1"

# ---------------------------------------------------------------------------
# Controlled vocabularies (this schema's closed sets)
# ---------------------------------------------------------------------------

#: The three node classes of the functional degree network.
NODE_KINDS = [
    "degree_triad",       # one of the 7 diatonic triads of a journey key
    "function_group",     # a T / PD-S / D functional family within a key
    "key_hub",            # the journey key itself (one per panel)
]

#: Relationship vocabulary *implemented* by the functional graph builder.
IMPLEMENTED_RELATIONS = [
    "function_member",    # degree -> its function group (I -> T, ii -> PD/S)
    "resolves_to",        # dominant-function pull home (V -> I, vii° -> I)
    "prepares",           # predominant approach (ii -> V, IV -> V)
    "tonic_substitute",   # vi <-> I, iii <-> I (shared chord tones)
    "deceptive_to",       # the deceptive resolution V -> vi
    "shared_triad",       # pitch-class-identical triads across panels
    "fifth_relation",     # adjacent journey keys a perfect fifth apart
    "in_key",             # degree -> its key hub (panel membership overlay)
]

#: Relationship vocabulary *reserved* (named now, generated by a future layer).
RESERVED_RELATIONS = [
    "modulation_path_to",
    "borrowed_from_parallel",
]

#: Every relation a template may legally name (implemented + reserved).
ALL_RELATIONS = IMPLEMENTED_RELATIONS + RESERVED_RELATIONS

#: The deterministic edge-generation passes the functional builder runs.
GENERATION_RULES = [
    "function_member_edges",   # 1. degree -> function group membership
    "resolution_edges",        # 2. V -> I, vii° -> I
    "preparation_edges",       # 3. ii -> V, IV -> V
    "substitute_edges",        # 4. vi <-> I, iii <-> I
    "deceptive_edges",         # 5. V -> vi
    "in_key_edges",            # 6. degree -> key hub (default-off overlay)
    "fifth_relation_edges",    # 7. adjacent panels by fifths
    "shared_triad_edges",      # 8. same pitch-class set across panels
]

#: The visual classes (node colours) of this network's palette.
VISUAL_CLASSES = ["emerald", "violet", "amber"]

#: The panel modes a functional template may declare.  ``minor`` panels use
#: the *harmonic* minor chord set (the real V / vii°, ticket 13 / G2a) while
#: the key context stays natural minor.  This is template metadata, not a
#: vocabulary widening: kinds/relations/rules above stay frozen.
PANEL_MODES = ["major", "minor"]

#: The three merged function groups (T / PD-S / D), in T->PD->D order.
#: The engine's five per-degree ``function_label`` values collapse onto these
#: (the builder owns that mapping); ``mediant`` is grouped as a tonic
#: substitute, with each node's explanation stating the ambiguity.
FUNCTION_GROUPS = ["tonic", "predominant", "dominant"]

#: Short badge / long display labels for the function groups -- derived from the shared
#: vocabulary (never hand-edit; ticket 01 / plan F1).
FUNCTION_GROUP_SHORT = {g: INTERNAL_FAMILY_SHORT[g] for g in FUNCTION_GROUPS}
FUNCTION_GROUP_LABELS = {g: internal_family_label(g) for g in FUNCTION_GROUPS}


# ---------------------------------------------------------------------------
# Schema dataclasses
# ---------------------------------------------------------------------------

@dataclass
class PanelLayoutRule:
    """How one node class is drawn inside a key panel (radius only -- the
    functional *positions* are template-level data shared by all panels)."""

    kind: str
    node_radius: float = 20.0
    description: str = ""

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class FunctionalNetworkTemplate:
    """A serialisable topological template for one functional degree network.

    Layout model: one panel per journey key, panels laid out left-to-right in
    circle-of-fifths order (the builder computes each panel's x-origin from
    ``panel_width``); inside a panel every degree / function group / hub has a
    fixed ``(dx, dy)`` offset.  All coordinates are computed in Python -- the
    JS renderer stays layout-free.
    """

    template_id: str
    title: str
    description: str
    node_classes: List[NodeClass]
    edge_classes: List[EdgeClass]
    layout_rules: List[PanelLayoutRule]
    generation_rules: List[str]
    #: The journey keys (major tonics) -- one panel each.  Display order is
    #: recomputed by fifths in the builder; this is the *pedagogical* order
    #: (C first: the journey starts there).
    journey_keys: List[str] = field(default_factory=list)
    #: Horizontal distance between adjacent panel centres.
    panel_width: float = 470.0
    #: Per-degree ``[dx, dy]`` offsets inside a panel, indexed 0..6 (I..vii°).
    #: PD/S column left, D column right, T cluster bottom-centre.
    degree_offsets: List[List[float]] = field(default_factory=list)
    #: Function-group ``[dx, dy]`` offsets, keyed by ``FUNCTION_GROUPS``.
    function_offsets: Dict[str, List[float]] = field(default_factory=dict)
    #: The key hub's ``[dx, dy]`` offset (top-centre of the panel).
    hub_offset: List[float] = field(default_factory=lambda: [0.0, -195.0])
    launch_rules: Dict[str, Any] = field(default_factory=dict)
    #: The panel mode: every journey key is a major key ("major") or a minor
    #: key ("minor", harmonic-minor chord set).  One journey = one mode; a
    #: mixed journey would need two templates.
    mode: str = "major"
    schema: str = SCHEMA_VERSION

    # -- lookups ---------------------------------------------------------
    def node_class(self, kind: str) -> NodeClass:
        for nc in self.node_classes:
            if nc.kind == kind:
                return nc
        raise KeyError(f"no node class for kind {kind!r}")

    def edge_class(self, relation: str) -> EdgeClass:
        for ec in self.edge_classes:
            if ec.relation == relation:
                return ec
        raise KeyError(f"no edge class for relation {relation!r}")

    def layout_for(self, kind: str) -> PanelLayoutRule:
        for lr in self.layout_rules:
            if lr.kind == kind:
                return lr
        raise KeyError(f"no layout rule for kind {kind!r}")

    def kinds(self) -> List[str]:
        return [nc.kind for nc in self.node_classes]

    def relations(self) -> List[str]:
        return [ec.relation for ec in self.edge_classes]

    def implemented_relations(self) -> List[str]:
        return [ec.relation for ec in self.edge_classes if ec.implemented]

    # -- validation ------------------------------------------------------
    def validate(self) -> None:
        """Raise :class:`ValueError` on any malformed / unknown-vocabulary field.

        Mirrors :meth:`harmony.network_template.HarmonicNetworkTemplate.validate`
        against *this* module's closed sets, plus the panel-layout invariants
        (7 degree offsets; one offset per function group; unique journey keys).
        """
        if not self.template_id:
            raise ValueError("template requires a non-empty template_id")
        if not self.title:
            raise ValueError("template requires a non-empty title")
        if not self.node_classes:
            raise ValueError("template requires at least one node class")
        if not self.edge_classes:
            raise ValueError("template requires at least one edge class")
        if not self.layout_rules:
            raise ValueError("template requires layout rules")

        seen_kinds = set()
        for nc in self.node_classes:
            if nc.kind not in NODE_KINDS:
                raise ValueError(
                    f"unknown node class {nc.kind!r}; expected one of {NODE_KINDS}")
            if nc.kind in seen_kinds:
                raise ValueError(f"duplicate node class {nc.kind!r}")
            seen_kinds.add(nc.kind)
            if nc.visual_class not in VISUAL_CLASSES:
                raise ValueError(
                    f"unknown visual class {nc.visual_class!r} for {nc.kind!r}; "
                    f"expected one of {VISUAL_CLASSES}")

        for ec in self.edge_classes:
            if ec.relation not in ALL_RELATIONS:
                raise ValueError(
                    f"unknown edge relation {ec.relation!r}; expected one of "
                    f"{ALL_RELATIONS}")
            if ec.relation in RESERVED_RELATIONS and ec.implemented:
                raise ValueError(
                    f"relation {ec.relation!r} is reserved and cannot be marked "
                    f"implemented")

        for rule in self.generation_rules:
            if rule not in GENERATION_RULES:
                raise ValueError(
                    f"unknown generation rule {rule!r}; expected one of "
                    f"{GENERATION_RULES}")

        layout_kinds = set()
        for lr in self.layout_rules:
            if lr.kind not in seen_kinds:
                raise ValueError(
                    f"layout rule for {lr.kind!r} has no matching node class")
            if lr.kind in layout_kinds:
                raise ValueError(f"duplicate layout rule for {lr.kind!r}")
            layout_kinds.add(lr.kind)
        missing = seen_kinds - layout_kinds
        if missing:
            raise ValueError(f"node classes missing a layout rule: {sorted(missing)}")

        if self.mode not in PANEL_MODES:
            raise ValueError(
                f"unknown panel mode {self.mode!r}; expected one of {PANEL_MODES}")

        if not self.journey_keys:
            raise ValueError("template requires at least one journey key")
        if len(set(self.journey_keys)) != len(self.journey_keys):
            raise ValueError(f"duplicate journey keys: {self.journey_keys}")

        if len(self.degree_offsets) != 7:
            raise ValueError(
                f"degree_offsets must cover the 7 diatonic degrees "
                f"(got {len(self.degree_offsets)})")
        for off in self.degree_offsets:
            if len(off) != 2:
                raise ValueError(f"degree offset {off!r} is not an [x, y] pair")
        if sorted(self.function_offsets) != sorted(FUNCTION_GROUPS):
            raise ValueError(
                f"function_offsets must be keyed exactly by {FUNCTION_GROUPS} "
                f"(got {sorted(self.function_offsets)})")
        for grp, off in self.function_offsets.items():
            if len(off) != 2:
                raise ValueError(f"function offset {grp}: {off!r} is not [x, y]")
        if len(self.hub_offset) != 2:
            raise ValueError(f"hub_offset {self.hub_offset!r} is not an [x, y] pair")
        if self.panel_width <= 0:
            raise ValueError("panel_width must be positive")

    # -- serialisation ---------------------------------------------------
    def to_dict(self) -> Dict:
        return {
            "schema": self.schema,
            "template_id": self.template_id,
            "title": self.title,
            "description": self.description,
            "node_classes": [nc.to_dict() for nc in self.node_classes],
            "edge_classes": [ec.to_dict() for ec in self.edge_classes],
            "layout_rules": [lr.to_dict() for lr in self.layout_rules],
            "generation_rules": list(self.generation_rules),
            "journey_keys": list(self.journey_keys),
            "panel_width": self.panel_width,
            "degree_offsets": [list(o) for o in self.degree_offsets],
            "function_offsets": {k: list(v) for k, v in self.function_offsets.items()},
            "hub_offset": list(self.hub_offset),
            "launch_rules": dict(self.launch_rules),
            "mode": self.mode,
        }

    @classmethod
    def from_dict(cls, d: Dict) -> "FunctionalNetworkTemplate":
        tpl = cls(
            template_id=d["template_id"],
            title=d["title"],
            description=d.get("description", ""),
            node_classes=[NodeClass(**nc) for nc in d.get("node_classes", [])],
            edge_classes=[EdgeClass(**ec) for ec in d.get("edge_classes", [])],
            layout_rules=[PanelLayoutRule(**lr) for lr in d.get("layout_rules", [])],
            generation_rules=list(d.get("generation_rules", [])),
            journey_keys=list(d.get("journey_keys", [])),
            panel_width=float(d.get("panel_width", 470.0)),
            degree_offsets=[list(o) for o in d.get("degree_offsets", [])],
            function_offsets={k: list(v)
                              for k, v in d.get("function_offsets", {}).items()},
            hub_offset=list(d.get("hub_offset", [0.0, -195.0])),
            launch_rules=dict(d.get("launch_rules", {})),
            mode=d.get("mode", "major"),
            schema=d.get("schema", SCHEMA_VERSION),
        )
        tpl.validate()
        return tpl


# ---------------------------------------------------------------------------
# The first concrete template
# ---------------------------------------------------------------------------

#: Default journey keys: 4 major keys with no enharmonic seam (v1 is major
#: only; minor panels + modulation paths are the natural v2).
DEFAULT_JOURNEY_KEYS = ["C", "G", "D", "F"]

#: Default *minor* journey keys (v2): the relative minors of the v1 journey
#: (Am/Em/Dm/Bm for C/G/F/D) -- the same no-enharmonic-seam neighbourhood of
#: the circle, one key signature apart each.
DEFAULT_MINOR_JOURNEY_KEYS = ["A", "E", "D", "B"]

#: Functional positions inside a panel (y grows downward), shared by every
#: journey template: PD/S column left, D column right, T cluster
#: bottom-centre.  Indexed 0..6 (I..vii° / i..vii°).
_PANEL_DEGREE_OFFSETS = [
    [0.0, 95.0],       # 0 tonic       -- centre
    [-115.0, -85.0],   # 1 supertonic  -- PD/S column, top
    [115.0, 140.0],    # 2 mediant     -- orbiting the tonic (substitute)
    [-160.0, -5.0],    # 3 subdominant -- PD/S column, lower
    [115.0, -85.0],    # 4 dominant    -- D column, top
    [-115.0, 140.0],   # 5 submediant  -- orbiting the tonic (substitute)
    [160.0, -5.0],     # 6 leading/subtonic -- D column, lower
]

_PANEL_FUNCTION_OFFSETS = {
    "tonic": [0.0, 200.0],
    "predominant": [-195.0, -145.0],
    "dominant": [195.0, -145.0],
}

_PANEL_HUB_OFFSET = [0.0, -195.0]


def _panel_layout_rules() -> List[PanelLayoutRule]:
    return [
        PanelLayoutRule("degree_triad", node_radius=22.0,
                        description="Degree triads at functional positions."),
        PanelLayoutRule("function_group", node_radius=25.0,
                        description="Function-family badges orbiting the panel."),
        PanelLayoutRule("key_hub", node_radius=27.0,
                        description="The key hub at the top of its panel."),
    ]


def _reserved_edge_classes() -> List[EdgeClass]:
    """The reserved vocabulary every journey template names but never
    generates -- shared verbatim by the major and minor factories."""
    return [
        EdgeClass("modulation_path_to", "Modulation path to", directed=True,
                  implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
        EdgeClass("borrowed_from_parallel", "Borrowed from parallel",
                  directed=True, implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
    ]


def _triad_launch_rules() -> Dict[str, Any]:
    # Everything in these graphs is a real triad drill.
    return {
        "launchable_kinds": ["degree_triad", "function_group", "key_hub"],
        "reserved_kinds": [],
        "reserved_reason": "",
    }


def functional_degree_network_v1(
        keys: "tuple[str, ...] | List[str]" = ("C", "G", "D", "F"),
) -> FunctionalNetworkTemplate:
    """The staged functional degree network over a few major journey keys.

    One panel per key.  Inside a panel, degrees sit in *functional* positions,
    not scale order -- the T→PD→D→T cycle the eye can follow::

                [ii]──prepares──▶[V]          PD/S column   D column
           [IV]─┘                 │ [vii°]
             ▲                    ▼resolves_to
           [vi]···substitute···▶[I]◀···[iii]   T cluster (I centre, vi/iii orbit)

    Every degree node is a real, launchable diatonic triad; function groups
    and key hubs launch their family / full-key drills.  There are **no
    reserved drills anywhere in this graph** -- everything is triad-based,
    which is the whole point.
    """
    node_classes = [
        NodeClass("degree_triad", "Diatonic degree", "emerald", "#34d399",
                  "One of the seven diatonic triads of a journey key, placed "
                  "by harmonic function (tonic cluster bottom-centre, "
                  "predominants left, dominants right)."),
        NodeClass("function_group", "Function group", "violet", "#a78bfa",
                  f"A functional family within one key: the "
                  f"{FUNCTION_GROUP_LABELS['tonic']} (I, vi, iii), the "
                  f"{FUNCTION_GROUP_LABELS['predominant']} (ii, IV) or the "
                  f"{FUNCTION_GROUP_LABELS['dominant']} (V, vii°). "
                  "The iii chord is grouped as a tonic substitute; its "
                  "explanation states the ambiguity."),
        NodeClass("key_hub", "Key hub", "amber", "#fbbf24",
                  "A journey key (one per panel). Launches the full-key "
                  "seven-triad drill."),
    ]

    # Edge visual classes deliberately reuse the harmonic_network.js /
    # harmonic_network.css palette keys (fifth / resolve / leading / relative /
    # shared / samepc / function / atlas / reserved) so the unmodified renderer
    # colours and dashes them correctly.
    edge_classes = [
        EdgeClass("function_member", "Member of function", directed=False,
                  visual_class="function", default_visible=True,
                  description="A degree belongs to a functional family "
                              "(I/vi/iii → T, ii/IV → PD/S, V/vii° → D)."),
        EdgeClass("resolves_to", "Resolves to", directed=True,
                  visual_class="resolve", default_visible=True,
                  description="Dominant-function tension resolving home "
                              "(V → I, vii° → I)."),
        EdgeClass("prepares", "Prepares", directed=True,
                  visual_class="leading", default_visible=True,
                  description="A predominant approaching the dominant "
                              "(ii → V, IV → V)."),
        EdgeClass("tonic_substitute", "Tonic substitute", directed=False,
                  visual_class="relative", default_visible=True,
                  description="vi and iii share two chord tones with I and "
                              "can stand in for it."),
        EdgeClass("deceptive_to", "Deceptive resolution", directed=True,
                  visual_class="shared", default_visible=True,
                  description="V resolving deceptively to vi instead of I "
                              "(the deceptive cadence)."),
        EdgeClass("shared_triad", "Same triad in another key", directed=False,
                  visual_class="samepc", default_visible=True,
                  description="Pitch-class-identical triads across panels: "
                              "one shape, several functions (C:I ≡ G:IV ≡ "
                              "F:V)."),
        EdgeClass("fifth_relation", "Fifth relation", directed=True,
                  visual_class="fifth", default_visible=True,
                  description="Adjacent journey keys a perfect fifth apart."),
        EdgeClass("in_key", "In key", directed=True,
                  visual_class="atlas", default_visible=False,
                  description="A degree belongs to its key panel (default-off "
                              "overlay; the panel grouping already shows it)."),
    ] + _reserved_edge_classes()

    return FunctionalNetworkTemplate(
        template_id="functional_degree_network_v1",
        title="Functional degree network (staged journey)",
        description=(
            "A practice-first harmonic network over a few major journey keys: "
            "every diatonic degree is a real graph node laid out by harmonic "
            "function (T / PD-S / D), function groups and key hubs orbit each "
            "panel, and resolution / preparation / substitution / deception "
            "arrows wire the functional cycle together. Pitch-class-identical "
            "triads are linked across panels (one shape, several functions). "
            "The graph reveals itself in guided stages driven by the Harmony "
            "Trainer -- playing is what lights the nodes. Derived entirely "
            "from the theory engine; triads only, so every node is launchable."),
        node_classes=node_classes,
        edge_classes=edge_classes,
        layout_rules=_panel_layout_rules(),
        generation_rules=list(GENERATION_RULES),
        journey_keys=list(keys),
        panel_width=470.0,
        degree_offsets=[list(o) for o in _PANEL_DEGREE_OFFSETS],
        function_offsets={k: list(v)
                          for k, v in _PANEL_FUNCTION_OFFSETS.items()},
        hub_offset=list(_PANEL_HUB_OFFSET),
        launch_rules=_triad_launch_rules(),
    )


# ---------------------------------------------------------------------------
# The v2 minor journey template (ticket 15 / plan G2c)
# ---------------------------------------------------------------------------

def functional_degree_network_minor_v2(
        keys: "tuple[str, ...] | List[str]" = ("A", "E", "D", "B"),
) -> FunctionalNetworkTemplate:
    """The staged functional degree network over a few *minor* journey keys.

    Registered through the registry seam as a new template -- the frozen v1
    vocabulary is reused, never widened, and the v1 template is untouched
    (docs/curriculum_expansion_plan.md section 9.6).

    Same panel geometry and stage machine as v1, but every panel is a minor
    key whose chords come from **harmonic minor** (ticket 13 / G2a): the
    dominant column holds the *real* minor V (major triad on 5, raised
    leading tone) and vii° -- not natural minor's modal v / VII.  The key
    context stays natural minor (the raised 7 is a scale form, not a key
    signature), which is exactly how the builder claims its Atlas refs::

              [ii°]──prepares──▶[V]          PD/S column   D column
          [iv]─┘                 │ [vii°]
            ▲                    ▼resolves_to
          [VI]···substitute···▶[i]◀···[III+]  T cluster (i centre, VI/III+ orbit)

    Every degree node is a real, launchable harmonic-minor triad; there are
    no reserved drills anywhere in this graph either.
    """
    node_classes = [
        NodeClass("degree_triad", "Diatonic degree", "emerald", "#34d399",
                  "One of the seven harmonic-minor triads of a journey key, "
                  "placed by harmonic function (tonic cluster bottom-centre, "
                  "predominants left, dominants right). The dominant column "
                  "holds the real minor V: harmonic minor's raised leading "
                  "tone makes it a major triad."),
        NodeClass("function_group", "Function group", "violet", "#a78bfa",
                  f"A functional family within one minor key: the "
                  f"{FUNCTION_GROUP_LABELS['tonic']} (i, VI, III+), the "
                  f"{FUNCTION_GROUP_LABELS['predominant']} (ii°, iv) or the "
                  f"{FUNCTION_GROUP_LABELS['dominant']} (V, vii°). "
                  "The augmented III+ is grouped as a tonic substitute; its "
                  "explanation states how fragile that grouping is."),
        NodeClass("key_hub", "Key hub", "amber", "#fbbf24",
                  "A minor journey key (one per panel). Launches the "
                  "full-key seven-triad harmonic-minor drill."),
    ]

    # Same renderer palette keys as v1 (the JS colours/dashes stay correct);
    # descriptions tell the minor story.
    edge_classes = [
        EdgeClass("function_member", "Member of function", directed=False,
                  visual_class="function", default_visible=True,
                  description="A degree belongs to a functional family "
                              "(i/VI/III+ → T, ii°/iv → PD/S, V/vii° → D)."),
        EdgeClass("resolves_to", "Resolves to", directed=True,
                  visual_class="resolve", default_visible=True,
                  description="Dominant-function tension resolving home "
                              "(V → i, vii° → i) -- the pull harmonic "
                              "minor's raised leading tone exists to create."),
        EdgeClass("prepares", "Prepares", directed=True,
                  visual_class="leading", default_visible=True,
                  description="A predominant approaching the dominant "
                              "(ii° → V, iv → V)."),
        EdgeClass("tonic_substitute", "Tonic substitute", directed=False,
                  visual_class="relative", default_visible=True,
                  description="VI and III+ share two chord tones with i and "
                              "can stand in for it (III+ only barely -- see "
                              "its node)."),
        EdgeClass("deceptive_to", "Deceptive resolution", directed=True,
                  visual_class="shared", default_visible=True,
                  description="V resolving deceptively to VI instead of i "
                              "(the minor-mode deceptive cadence)."),
        EdgeClass("shared_triad", "Same triad in another key", directed=False,
                  visual_class="samepc", default_visible=True,
                  description="Pitch-class-identical triads across panels: "
                              "one shape, several functions (Am is i at home "
                              "and iv in E minor)."),
        EdgeClass("fifth_relation", "Fifth relation", directed=True,
                  visual_class="fifth", default_visible=True,
                  description="Adjacent minor journey keys a perfect fifth "
                              "apart."),
        EdgeClass("in_key", "In key", directed=True,
                  visual_class="atlas", default_visible=False,
                  description="A degree belongs to its key panel (default-off "
                              "overlay; the panel grouping already shows it)."),
    ] + _reserved_edge_classes()

    return FunctionalNetworkTemplate(
        template_id="functional_degree_network_minor_v2",
        title="Functional degree network — minor journey",
        description=(
            "The minor-key sibling of the staged functional journey: every "
            "panel is a minor key whose seven triads come from harmonic "
            "minor, so the dominant column holds the REAL minor V (a major "
            "triad -- the raised leading tone) and vii°, not natural minor's "
            "modal v/VII. Function groups, resolution / preparation / "
            "substitution / deception arrows and cross-panel shared-triad "
            "links work exactly as in the major journey, and the graph "
            "reveals itself in the same guided stages. Derived entirely from "
            "the theory engine; triads only, so every node is launchable."),
        node_classes=node_classes,
        edge_classes=edge_classes,
        layout_rules=_panel_layout_rules(),
        generation_rules=list(GENERATION_RULES),
        journey_keys=list(keys),
        panel_width=470.0,
        degree_offsets=[list(o) for o in _PANEL_DEGREE_OFFSETS],
        function_offsets={k: list(v)
                          for k, v in _PANEL_FUNCTION_OFFSETS.items()},
        hub_offset=list(_PANEL_HUB_OFFSET),
        launch_rules=_triad_launch_rules(),
        mode="minor",
    )


# ---------------------------------------------------------------------------
# Template registry (future functional topologies register here)
# ---------------------------------------------------------------------------

TEMPLATES = {
    "functional_degree_network_v1": functional_degree_network_v1,
    "functional_degree_network_minor_v2": functional_degree_network_minor_v2,
}

DEFAULT_TEMPLATE_ID = "functional_degree_network_v1"


def get_template(template_id: Optional[str] = None) -> FunctionalNetworkTemplate:
    """Return a validated functional template by id (default: the v1 journey)."""
    tid = template_id or DEFAULT_TEMPLATE_ID
    if tid not in TEMPLATES:
        raise KeyError(
            f"unknown functional template {tid!r}; available: {sorted(TEMPLATES)}")
    tpl = TEMPLATES[tid]()
    tpl.validate()
    return tpl


def load_template(data: Dict) -> FunctionalNetworkTemplate:
    """Load (and validate) a functional template from a serialised dict."""
    return FunctionalNetworkTemplate.from_dict(data)
