"""Topological templates for the Harmonic Network / Tonal Graph layer.

The **Harmonic Network** is a *relational* layer on top of the existing
pedagogical map (Circle of Fifths → Interactive Harmony Atlas → Music Theory
Laboratory / Curriculum).  Where the Atlas answers "what is the invariant degree
pattern, and how does it transpose", the Network answers "how are *whole keys,
relative minors, dominant sevenths and leading-tone diminished triads* wired
together by fifths, relative relations and functional pull".

This module is the **schema** for that layer.  A
:class:`HarmonicNetworkTemplate` is a pure, serialisable description of:

* the node *classes* (major key / minor key / dominant seventh / diminished),
  each with a visual class (the reference image's pink / blue / yellow / purple);
* the edge *classes* (the relationship vocabulary), split into implemented and
  reserved relations;
* the layout rules (concentric rings + angular placement by fifth index);
* which deterministic *generation rules* the builder should run;
* the launch rules (what is launchable vs. reserved).

It deliberately contains **no theory tables**: the actual nodes/edges are
generated by :mod:`harmony.harmonic_network` from the live theory engine
(:mod:`theory.diatonic_harmony`) so the network can never drift from the rest of
the app.  The first concrete template,
``dominant_diminished_relative_network_v1``, reconstructs the topology of the
Brian-Callipari-style reference image (``images/571334612_*.jpg``) as a *formal
music-theory graph*, not an image trace.

Later topologies are added by writing another :class:`HarmonicNetworkTemplate`
with the same schema and registering it in :data:`TEMPLATES`.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional


SCHEMA_VERSION = "harmony-network-template/v1"

# ---------------------------------------------------------------------------
# Controlled vocabularies (the schema's closed sets)
# ---------------------------------------------------------------------------

#: The node classes across all templates.  A template uses a subset.  The first four are the
#: legacy reference-image classes; the rest (key/chord/function/class/degree/voicing) are the
#: semantic-level classes the bidirectional-mapping templates introduce (plan section 13.3).
NODE_KINDS = [
    "major_key",
    "minor_key",
    "dominant_seventh",
    "diminished_triad",
    "key_center",
    "diatonic_triad",
    "function_family",
    "quality_class",
    "degree_class",
    "inversion_state",
]

#: Ontological level / role a node class occupies (plan section 7). Additive metadata on
#: :class:`NodeClass`; ``""`` means "unspecified" (the legacy classes leave them blank).
SEMANTIC_LEVELS = ["key", "chord", "function", "class", "voicing", "path"]
ENTITY_ROLES = ["anchor", "instance", "family", "state", "reference"]

#: Relationship vocabulary that is *implemented* by a graph builder rule.  The first eleven are
#: the legacy relations; the rest are the membership / functional-motion / voicing relations the
#: new templates add (plan section 13.3).
IMPLEMENTED_RELATIONS = [
    "fifth_relation",
    "relative_minor_of",
    "relative_major_of",
    "dominant_of",
    "resolves_to",
    "leading_tone_to",
    "shares_scale_with",
    "same_pitch_class",
    "same_function",
    "trainer_drill_available",
    "atlas_node_available",
    "belongs_to_key",
    "member_of_function",
    "prepares",
    "prolongs",
    "substitutes_for",
    "inversion_of",
    "voice_leads_to",
    "instance_of",       # a concrete chord is an instance of an abstract degree / quality class
]

#: The eleven relations the legacy reference template declares (used to keep the legacy
#: fingerprint pinned while the shared vocabulary grows).
LEGACY_IMPLEMENTED_RELATIONS = [
    "fifth_relation", "relative_minor_of", "relative_major_of", "dominant_of",
    "resolves_to", "leading_tone_to", "shares_scale_with", "same_pitch_class",
    "same_function", "trainer_drill_available", "atlas_node_available",
]

#: Relationship vocabulary that is *reserved* (named now, generated later).
RESERVED_RELATIONS = [
    "secondary_dominant_of",
    "borrowed_from_parallel",
    "tritone_substitute_of",
    "common_tone_diminished",
    "enharmonic_equivalent_of",
    "modulation_path_to",
]

#: Every relation a template may legally name (implemented + reserved).
ALL_RELATIONS = IMPLEMENTED_RELATIONS + RESERVED_RELATIONS

#: The deterministic EDGE-generation passes the builder knows how to run (dispatched to a
#: ``_rule_<name>`` method).
GENERATION_RULES = [
    "major_circle_by_fifths",       # 1. major keys connect by fifths/fourths
    "relative_minor_edges",         # 2. C major <-> A minor, ...
    "dominant_seventh_resolution_edges",  # 3. G7 -> C, D7 -> G, ...
    "leading_tone_diminished_edges",      # 4. B° -> C, F#° -> G, ...
    "shared_scale_edges",           # 5. shared-scale relations (optional layer)
    "same_function_edges",          # V7 and vii° share the dominant function
    "same_pitch_class_edges",       # cross-class same-root overlay (optional)
    "integration_overlays",         # trainer_drill_available / atlas_node_available
    # bidirectional-mapping templates:
    "diatonic_membership_edges",    # triad belongs_to_key + member_of_function (core template)
    "core_function_motion_edges",   # supported V->I / ii->V / vii°->I motions between triads
    "inversion_adjacency_edges",    # inversion_of / voice_leads_to (inversion template)
    # post-MVP orbit / class / equivalence templates:
    "transposition_orbit_edges",    # each per-key instance instance_of the abstract degree
    "quality_membership_edges",     # each triad instance_of its quality class
    "functional_equivalence_edges", # V member_of dominant, V7 substitutes_for V, V7 same_function vii°
]

#: The deterministic NODE-generation passes (dispatched to a ``_node_<name>`` method). A template
#: with no ``node_generation_rules`` falls back to the legacy 4-kind builder for compatibility.
NODE_GENERATION_RULES = [
    "legacy_key_dom_dim_nodes",     # the reference-image 48-node builder (default)
    "core_key_center_node",         # one key-centre anchor
    "core_diatonic_triad_nodes",    # the seven exact diatonic triads
    "core_function_family_nodes",   # tonic / predominant / dominant families
    "inversion_identity_node",      # one chord-identity anchor (inversion template)
    "inversion_state_nodes",        # root / 1st / 2nd inversion voicing states
    "transposition_orbit_nodes",    # abstract degree class + per-key triad instances
    "quality_class_nodes",          # quality classes + a key's diatonic triads
    "functional_equivalence_nodes", # dominant family + V (triad) / V7 (reserved) / vii°
]

#: The visual classes (colours). The first four are the reference image's palette; the rest are
#: the semantic-level classes the new templates use.
VISUAL_CLASSES = ["pink", "blue", "yellow", "purple",
                  "slate", "teal", "amber", "green", "rose"]


# ---------------------------------------------------------------------------
# Schema dataclasses
# ---------------------------------------------------------------------------

@dataclass
class NodeClass:
    """One node class: a kind + how it is drawn + what it means.

    ``semantic_level`` / ``entity_role`` make the ontological distinction explicit (a key node is
    an *anchor*, a triad node a chord *instance*), and ``canonical_ref`` names the Atlas concept
    the class mirrors.  They are additive; the legacy classes leave them blank.
    """

    kind: str
    label: str
    visual_class: str            # pink | blue | yellow | purple | slate | teal | amber | ...
    color: str                   # hex fill
    description: str = ""
    semantic_level: str = ""     # key | chord | function | class | voicing | path
    entity_role: str = ""        # anchor | instance | family | state | reference
    canonical_ref: str = ""      # e.g. an Atlas id family this class mirrors

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class EdgeClass:
    """One relationship type in the network's vocabulary."""

    relation: str
    label: str
    directed: bool = True
    implemented: bool = True     # False => reserved (no edges generated yet)
    visual_class: str = "default"
    default_visible: bool = True
    description: str = ""

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class LayoutRule:
    """Where a node class sits: a concentric ring + per-spoke offsets."""

    kind: str
    ring: str                    # outer | inner | dominant | central (label only)
    radius: float                # distance from centre
    angle_offset: float = 0.0    # degrees added to the spoke angle (fifth index)
    node_radius: float = 18.0    # drawn circle radius

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class HarmonicNetworkTemplate:
    """A serialisable topological template (the schema of one network)."""

    template_id: str
    title: str
    description: str
    node_classes: List[NodeClass]
    edge_classes: List[EdgeClass]
    layout_rules: List[LayoutRule]
    generation_rules: List[str]
    #: The 12 circle-of-fifths *major* tonics, clockwise from the top, spelled
    #: the way the template wants them displayed (this is *layout data*, not a
    #: theory table -- every chord is still derived from the engine).
    center_keys: List[str] = field(default_factory=list)
    node_layers: List[str] = field(default_factory=list)
    launch_rules: Dict[str, Any] = field(default_factory=dict)
    #: Which NODE-generation passes the builder runs.  Empty => the legacy 4-kind builder (so the
    #: reference template keeps building unchanged).  Key-local templates list their own rules.
    node_generation_rules: List[str] = field(default_factory=list)
    #: How the builder lays nodes out (``concentric_fifths`` for the circle template,
    #: ``key_local`` for the parameterised triad/function/inversion templates).
    layout_strategy: str = "concentric_fifths"
    #: Declares the build-context parameters a parameterised template accepts (key/mode/degree...).
    context_schema: Dict[str, Any] = field(default_factory=dict)
    schema: str = SCHEMA_VERSION

    # -- lookups ---------------------------------------------------------
    def node_class(self, kind: str) -> NodeClass:
        for nc in self.node_classes:
            if nc.kind == kind:
                return nc
        raise KeyError(f"no node class for kind {kind!r}")

    def edge_class(self, relation: str) -> EdgeClass:
        for ec in self.edge_classes:
            if ec.relation == relation:
                return ec
        raise KeyError(f"no edge class for relation {relation!r}")

    def layout_for(self, kind: str) -> LayoutRule:
        for lr in self.layout_rules:
            if lr.kind == kind:
                return lr
        raise KeyError(f"no layout rule for kind {kind!r}")

    def kinds(self) -> List[str]:
        return [nc.kind for nc in self.node_classes]

    def relations(self) -> List[str]:
        return [ec.relation for ec in self.edge_classes]

    def implemented_relations(self) -> List[str]:
        return [ec.relation for ec in self.edge_classes if ec.implemented]

    # -- validation ------------------------------------------------------
    def validate(self) -> None:
        """Raise :class:`ValueError` on any malformed / unknown-vocabulary field.

        Checks (the schema's contract):
          * required scalar fields are present and non-empty;
          * every node class names a known kind (``NODE_KINDS``);
          * every edge class names a known relation (implemented or reserved);
          * every generation rule is recognised;
          * every node class has exactly one layout rule and vice-versa;
          * visual classes are from the known palette.
        """
        if not self.template_id:
            raise ValueError("template requires a non-empty template_id")
        if not self.title:
            raise ValueError("template requires a non-empty title")
        if not self.node_classes:
            raise ValueError("template requires at least one node class")
        if not self.edge_classes:
            raise ValueError("template requires at least one edge class")
        if not self.layout_rules:
            raise ValueError("template requires layout rules")

        seen_kinds = set()
        for nc in self.node_classes:
            if nc.kind not in NODE_KINDS:
                raise ValueError(
                    f"unknown node class {nc.kind!r}; expected one of {NODE_KINDS}")
            if nc.kind in seen_kinds:
                raise ValueError(f"duplicate node class {nc.kind!r}")
            seen_kinds.add(nc.kind)
            if nc.visual_class not in VISUAL_CLASSES:
                raise ValueError(
                    f"unknown visual class {nc.visual_class!r} for {nc.kind!r}; "
                    f"expected one of {VISUAL_CLASSES}")
            if nc.semantic_level and nc.semantic_level not in SEMANTIC_LEVELS:
                raise ValueError(
                    f"unknown semantic level {nc.semantic_level!r} for {nc.kind!r}; "
                    f"expected one of {SEMANTIC_LEVELS}")
            if nc.entity_role and nc.entity_role not in ENTITY_ROLES:
                raise ValueError(
                    f"unknown entity role {nc.entity_role!r} for {nc.kind!r}; "
                    f"expected one of {ENTITY_ROLES}")

        for ec in self.edge_classes:
            if ec.relation not in ALL_RELATIONS:
                raise ValueError(
                    f"unknown edge relation {ec.relation!r}; expected one of "
                    f"{ALL_RELATIONS}")
            # A reserved relation must not advertise itself as implemented.
            if ec.relation in RESERVED_RELATIONS and ec.implemented:
                raise ValueError(
                    f"relation {ec.relation!r} is reserved and cannot be marked "
                    f"implemented")

        for rule in self.generation_rules:
            if rule not in GENERATION_RULES:
                raise ValueError(
                    f"unknown generation rule {rule!r}; expected one of "
                    f"{GENERATION_RULES}")

        for rule in self.node_generation_rules:
            if rule not in NODE_GENERATION_RULES:
                raise ValueError(
                    f"unknown node generation rule {rule!r}; expected one of "
                    f"{NODE_GENERATION_RULES}")

        layout_kinds = set()
        for lr in self.layout_rules:
            if lr.kind not in seen_kinds:
                raise ValueError(
                    f"layout rule for {lr.kind!r} has no matching node class")
            layout_kinds.add(lr.kind)
        missing = seen_kinds - layout_kinds
        if missing:
            raise ValueError(f"node classes missing a layout rule: {sorted(missing)}")

    # -- serialisation ---------------------------------------------------
    def to_dict(self) -> Dict:
        return {
            "schema": self.schema,
            "template_id": self.template_id,
            "title": self.title,
            "description": self.description,
            "node_layers": list(self.node_layers),
            "node_classes": [nc.to_dict() for nc in self.node_classes],
            "edge_classes": [ec.to_dict() for ec in self.edge_classes],
            "layout_rules": [lr.to_dict() for lr in self.layout_rules],
            "generation_rules": list(self.generation_rules),
            "center_keys": list(self.center_keys),
            "launch_rules": dict(self.launch_rules),
            "node_generation_rules": list(self.node_generation_rules),
            "layout_strategy": self.layout_strategy,
            "context_schema": dict(self.context_schema),
        }

    @classmethod
    def from_dict(cls, d: Dict) -> "HarmonicNetworkTemplate":
        tpl = cls(
            template_id=d["template_id"],
            title=d["title"],
            description=d.get("description", ""),
            node_classes=[NodeClass(**nc) for nc in d.get("node_classes", [])],
            edge_classes=[EdgeClass(**ec) for ec in d.get("edge_classes", [])],
            layout_rules=[LayoutRule(**lr) for lr in d.get("layout_rules", [])],
            generation_rules=list(d.get("generation_rules", [])),
            center_keys=list(d.get("center_keys", [])),
            node_layers=list(d.get("node_layers", [])),
            launch_rules=dict(d.get("launch_rules", {})),
            node_generation_rules=list(d.get("node_generation_rules", [])),
            layout_strategy=d.get("layout_strategy", "concentric_fifths"),
            context_schema=dict(d.get("context_schema", {})),
            schema=d.get("schema", SCHEMA_VERSION),
        )
        tpl.validate()
        return tpl


# ---------------------------------------------------------------------------
# The first concrete template
# ---------------------------------------------------------------------------

#: 12 major tonics, clockwise from C at 12 o'clock, spelled to match the
#: reference image (sharps on the top half, flats on the bottom half, F# at the
#: 6-o'clock enharmonic seam).  Purely the *display order*; every relative
#: minor / dominant seventh / diminished triad is derived from the engine.
CIRCLE_OF_FIFTHS_MAJOR = [
    "C", "G", "D", "A", "E", "B", "F#", "Db", "Ab", "Eb", "Bb", "F",
]


def dominant_diminished_relative_network_v1() -> HarmonicNetworkTemplate:
    """Reconstruct the reference image's topology as a formal theory graph.

    Four concentric rings around a central crosshair:
      * **major keys** (pink) and their **relative minors** (blue) alternate on
        the outer ring, ordered by the circle of fifths;
      * each key's **dominant seventh** (yellow) sits on the same radial spoke,
        midway in;
      * each key's **leading-tone diminished triad** (purple) sits innermost.

    Arrows show functional pull: V7 → I and vii° → I (to both the major tonic
    and the same-pitch-class minor tonic across the field), giving the
    characteristic crossing resolution arcs of the reference image.
    """
    node_classes = [
        NodeClass("major_key", "Major key", "pink", "#ec4899",
                  "A major key (tonic). Outer ring, ordered by the circle of "
                  "fifths."),
        NodeClass("minor_key", "Relative minor", "blue", "#38bdf8",
                  "The relative minor of a major key (shares its key signature)."),
        NodeClass("dominant_seventh", "Dominant seventh", "yellow", "#facc15",
                  "The V7 of a key. A theoretical node: seventh-chord drills are "
                  "reserved (the engine is triad-based)."),
        NodeClass("diminished_triad", "Leading-tone diminished", "purple",
                  "#a855f7",
                  "The vii° (leading-tone) diminished triad of a key; a rootless "
                  "dominant that resolves to the tonic."),
    ]

    edge_classes = [
        EdgeClass("fifth_relation", "Fifth relation", directed=True,
                  visual_class="fifth", default_visible=True,
                  description="Adjacent major keys a perfect fifth apart."),
        EdgeClass("relative_minor_of", "Relative minor of", directed=False,
                  visual_class="relative", default_visible=True,
                  description="Major key → its relative minor."),
        EdgeClass("relative_major_of", "Relative major of", directed=False,
                  visual_class="relative", default_visible=True,
                  description="Relative minor → its relative major."),
        EdgeClass("dominant_of", "Dominant of", directed=True,
                  visual_class="dominant", default_visible=False,
                  description="A dominant seventh is the V7 of its tonic "
                              "(functional label twin of resolves_to)."),
        EdgeClass("resolves_to", "Resolves to", directed=True,
                  visual_class="resolve", default_visible=True,
                  description="Functional resolution (V7 → I, vii° → I)."),
        EdgeClass("leading_tone_to", "Leading-tone to", directed=True,
                  visual_class="leading", default_visible=True,
                  description="A diminished triad's leading tone resolves up to "
                              "the tonic."),
        EdgeClass("shares_scale_with", "Shares scale with", directed=False,
                  visual_class="shared", default_visible=False,
                  description="Diatonically related keys (relative + ii/iii/vi "
                              "minors). Optional layer to avoid clutter."),
        EdgeClass("same_pitch_class", "Same pitch class", directed=False,
                  visual_class="samepc", default_visible=False,
                  description="Nodes whose root is the same pitch class "
                              "(cross-class overlay)."),
        EdgeClass("same_function", "Same function", directed=False,
                  visual_class="function", default_visible=True,
                  description="V7 and vii° of a key share the dominant function "
                              "(vii° is a rootless V7)."),
        EdgeClass("trainer_drill_available", "Trainer drill available",
                  directed=True, visual_class="trainer", default_visible=False,
                  description="Points at the closest launchable Harmony Trainer "
                              "triad drill for this node."),
        EdgeClass("atlas_node_available", "Atlas node available", directed=True,
                  visual_class="atlas", default_visible=False,
                  description="Points at the related Interactive Harmony Atlas "
                              "concept node."),
        # Reserved vocabulary -- named now, generated by a future layer.
        EdgeClass("secondary_dominant_of", "Secondary dominant of", directed=True,
                  implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
        EdgeClass("borrowed_from_parallel", "Borrowed from parallel",
                  directed=True, implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
        EdgeClass("tritone_substitute_of", "Tritone substitute of", directed=True,
                  implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
        EdgeClass("common_tone_diminished", "Common-tone diminished",
                  directed=True, implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
        EdgeClass("enharmonic_equivalent_of", "Enharmonic equivalent of",
                  directed=False, implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
        EdgeClass("modulation_path_to", "Modulation path to", directed=True,
                  implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
    ]

    layout_rules = [
        LayoutRule("major_key", "outer", radius=300.0, angle_offset=0.0,
                   node_radius=21.0),
        LayoutRule("minor_key", "outer", radius=300.0, angle_offset=15.0,
                   node_radius=19.0),
        LayoutRule("dominant_seventh", "dominant", radius=192.0, angle_offset=0.0,
                   node_radius=18.0),
        LayoutRule("diminished_triad", "central", radius=112.0, angle_offset=0.0,
                   node_radius=17.0),
    ]

    return HarmonicNetworkTemplate(
        template_id="dominant_diminished_relative_network_v1",
        title="Dominant / diminished / relative-minor harmonic network",
        description=(
            "A topological reconstruction of the Brian-Callipari-style harmonic "
            "network: the 12 major keys and their relative minors on the outer "
            "ring (circle of fifths), each key's dominant seventh midway in, and "
            "each key's leading-tone diminished triad innermost. Resolution "
            "arrows (V7 → I, vii° → I) wire the field together. Reconstructed "
            "deterministically from the theory engine, not traced from the image."),
        node_classes=node_classes,
        edge_classes=edge_classes,
        layout_rules=layout_rules,
        generation_rules=[
            "major_circle_by_fifths",
            "relative_minor_edges",
            "dominant_seventh_resolution_edges",
            "leading_tone_diminished_edges",
            "same_function_edges",
            "shared_scale_edges",
            "same_pitch_class_edges",
            "integration_overlays",
        ],
        center_keys=list(CIRCLE_OF_FIFTHS_MAJOR),
        node_layers=["major_key", "minor_key", "dominant_seventh",
                     "diminished_triad"],
        launch_rules={
            # Triad-based drills are launchable; seventh-chord drills are reserved
            # until the engine grows seventh chords.
            "launchable_kinds": ["major_key", "minor_key", "diminished_triad"],
            "reserved_kinds": ["dominant_seventh"],
            "reserved_reason": (
                "The theory engine is triad-based; seventh-chord exercises are "
                "not implemented. Dominant-seventh nodes link to the closest "
                "available triad drill (the V→I resolution) instead."),
        },
    )


def core_triad_function_network_v1() -> HarmonicNetworkTemplate:
    """A parameterised, key-local graph of the seven exact diatonic triads by function.

    Unlike the reference template (whole keys + reserved sevenths), every node here is a real,
    launchable diatonic triad -- so a ``full_key`` drill maps to *exact* chord nodes instead of
    proxies, and ``Dm`` maps to ``hn:triad:C:major:1`` rather than the C key node.  Default
    context: C major (override via a :class:`~harmony.harmonic_network.NetworkBuildContext`).

    Topology: one key-centre anchor at the centre, three broad function-family nodes (tonic /
    predominant / dominant) around it, and the seven triads on the outer ring wired to their key
    (``belongs_to_key``) and function family (``member_of_function``), plus the supported
    functional motions (``ii/IV -> V``, ``V -> I``, ``vii° -> I``) as canonical theory edges.
    """
    node_classes = [
        NodeClass("key_center", "Key centre", "slate", "#64748b",
                  "The tonal centre / scale context. A key anchor -- NOT the tonic chord.",
                  semantic_level="key", entity_role="anchor", canonical_ref="scale"),
        NodeClass("diatonic_triad", "Diatonic triad", "teal", "#14b8a6",
                  "One of the seven exact diatonic triads of the key context.",
                  semantic_level="chord", entity_role="instance", canonical_ref="triad"),
        NodeClass("function_family", "Function family", "amber", "#f59e0b",
                  "A broad harmonic function (tonic / predominant / dominant) grouping its "
                  "member triads.", semantic_level="function", entity_role="family",
                  canonical_ref="function"),
    ]

    edge_classes = [
        EdgeClass("belongs_to_key", "Belongs to key", directed=True,
                  visual_class="membership", default_visible=True,
                  description="A diatonic triad belongs to its key context."),
        EdgeClass("member_of_function", "Member of function", directed=True,
                  visual_class="membership", default_visible=True,
                  description="A triad is a member of a broad function family."),
        EdgeClass("resolves_to", "Resolves to", directed=True,
                  visual_class="resolve", default_visible=True,
                  description="Functional resolution (V -> I, vii° -> I, plagal IV -> I)."),
        EdgeClass("leading_tone_to", "Leading-tone to", directed=True,
                  visual_class="leading", default_visible=True,
                  description="The vii° leading tone resolves up to the tonic."),
        EdgeClass("prepares", "Prepares", directed=True,
                  visual_class="prepare", default_visible=True,
                  description="A predominant prepares the dominant (ii/IV -> V)."),
        EdgeClass("prolongs", "Prolongs", directed=True,
                  visual_class="prolong", default_visible=False,
                  description="A chord prolongs the same function (reserved layer)."),
    ]

    layout_rules = [
        LayoutRule("key_center", "central", radius=0.0, angle_offset=0.0, node_radius=28.0),
        LayoutRule("function_family", "inner", radius=150.0, angle_offset=0.0, node_radius=22.0),
        LayoutRule("diatonic_triad", "outer", radius=300.0, angle_offset=0.0, node_radius=19.0),
    ]

    return HarmonicNetworkTemplate(
        template_id="core_triad_function_network_v1",
        title="Core triad / function network",
        description=(
            "A key-local graph of the seven exact diatonic triads, clustered by broad harmonic "
            "function around a key-centre anchor. Every triad is a real launchable node, so "
            "drills map to exact chord nodes. Derived deterministically from the theory engine "
            "for the active key context (default C major)."),
        node_classes=node_classes,
        edge_classes=edge_classes,
        layout_rules=layout_rules,
        generation_rules=[
            "diatonic_membership_edges",
            "core_function_motion_edges",
        ],
        node_generation_rules=[
            "core_key_center_node",
            "core_diatonic_triad_nodes",
            "core_function_family_nodes",
        ],
        layout_strategy="key_local",
        context_schema={"key": "C", "mode": "major"},
        center_keys=["C"],
        node_layers=["key_center", "function_family", "diatonic_triad"],
        launch_rules={
            "launchable_kinds": ["diatonic_triad", "key_center", "function_family"],
            "reserved_kinds": [],
            "reserved_reason": "",
        },
    )


def cadence_resolution_network_v1() -> HarmonicNetworkTemplate:
    """The core triad/function graph overlaid with first-class cadence *paths*.

    Reuses the exact diatonic-triad nodes and their supported functional-motion edges (so no chord
    node is duplicated per cadence), and adds a catalogue of ordered :class:`HarmonicPath` arcs
    (V-I, IV-I, ii-V-I, i-iv-v-i, ...) built by the network layer from the active key context.
    Each path launches a block/arpeggio trainer drill and a voice-leading Lab experiment; the
    active theory edge follows the trainer through the route.
    """
    tpl = core_triad_function_network_v1()
    tpl.template_id = "cadence_resolution_network_v1"
    tpl.title = "Cadence resolution network"
    tpl.description = (
        "The core diatonic-triad graph with a catalogue of cadence paths (authentic, plagal, "
        "deceptive and multi-chord routes) as first-class ordered arcs. Paths reuse the exact "
        "triad nodes rather than duplicating chords, and light up canonical theory edges only "
        "where the network independently supports them.")
    tpl.launch_rules = {**tpl.launch_rules, "path_catalogue": "cadence"}
    return tpl


def inversion_space_network_v1() -> HarmonicNetworkTemplate:
    """One chord identity with its three voicing states (root / 1st / 2nd inversion).

    Parameterised by key, mode and degree.  A central chord-identity anchor is surrounded by
    three inversion-state satellites (C, C/E, C/G); each state ``inversion_of`` the anchor and
    ``voice_leads_to`` the next.  The states execute in the Music Theory Lab (the root-position
    trainer cannot voice inversions), so no renderer is duplicated -- the graph mirrors the Lab's
    changing-bass measures (plan section 14.3).
    """
    node_classes = [
        NodeClass("diatonic_triad", "Chord identity", "teal", "#14b8a6",
                  "The invariant chord identity whose bass changes across inversions.",
                  semantic_level="chord", entity_role="reference", canonical_ref="triad"),
        NodeClass("inversion_state", "Inversion state", "rose", "#f43f5e",
                  "One voicing of the chord (root position / first / second inversion); same "
                  "chord identity, changing bass.",
                  semantic_level="voicing", entity_role="state", canonical_ref="triad"),
    ]
    edge_classes = [
        EdgeClass("inversion_of", "Inversion of", directed=True,
                  visual_class="inversion", default_visible=True,
                  description="A voicing state is an inversion of the chord identity."),
        EdgeClass("voice_leads_to", "Voice-leads to", directed=True,
                  visual_class="voicing", default_visible=True,
                  description="Smooth voice-leading to the adjacent inversion."),
    ]
    layout_rules = [
        LayoutRule("diatonic_triad", "central", radius=0.0, angle_offset=0.0, node_radius=28.0),
        LayoutRule("inversion_state", "inner", radius=150.0, angle_offset=0.0, node_radius=22.0),
    ]
    return HarmonicNetworkTemplate(
        template_id="inversion_space_network_v1",
        title="Inversion-space network",
        description=(
            "One chord identity and its three inversion voicings (C, C/E, C/G) as satellite "
            "states around a central anchor, with inversion-of and voice-leading edges. The "
            "voicings run in the Music Theory Lab; the chord's function never changes."),
        node_classes=node_classes,
        edge_classes=edge_classes,
        layout_rules=layout_rules,
        generation_rules=["inversion_adjacency_edges"],
        node_generation_rules=["inversion_identity_node", "inversion_state_nodes"],
        layout_strategy="key_local",
        context_schema={"key": "C", "mode": "major", "degree": "I"},
        center_keys=["C"],
        node_layers=["diatonic_triad", "inversion_state"],
        launch_rules={
            "launchable_kinds": ["inversion_state"],
            "reserved_kinds": [],
            "reserved_reason": "",
            "lab_concept": "inversion",
        },
    )


def transposition_orbit_network_v1() -> HarmonicNetworkTemplate:
    """One abstract degree orbiting a set of keys as exact per-key chord instances.

    A central key-invariant ``degree_class`` node (e.g. "V") is surrounded by the concrete
    realisation of that degree in each key (V-in-C = G, V-in-G = D, ...), each an exact
    diatonic-triad node.  A ``horizontal_degree`` drill maps onto these exactly; the runtime
    overlay is ``transpose_next`` -- a transposition, never a modulation (plan section 14.4).
    """
    node_classes = [
        NodeClass("degree_class", "Abstract degree", "green", "#22c55e",
                  "A key-invariant scale degree (the same pattern in every key).",
                  semantic_level="class", entity_role="reference", canonical_ref="degree"),
        NodeClass("diatonic_triad", "Degree instance", "teal", "#14b8a6",
                  "The abstract degree realised as an exact triad in one key.",
                  semantic_level="chord", entity_role="instance", canonical_ref="triad"),
    ]
    edge_classes = [
        EdgeClass("instance_of", "Instance of", directed=True,
                  visual_class="membership", default_visible=True,
                  description="A per-key triad is an instance of the abstract degree."),
    ]
    layout_rules = [
        LayoutRule("degree_class", "central", radius=0.0, angle_offset=0.0, node_radius=26.0),
        LayoutRule("diatonic_triad", "outer", radius=300.0, angle_offset=0.0, node_radius=18.0),
    ]
    return HarmonicNetworkTemplate(
        template_id="transposition_orbit_network_v1",
        title="Transposition-orbit network",
        description=(
            "One abstract scale degree orbiting a set of keys: the invariant degree at the "
            "centre, its exact per-key chord instances around the ring. A horizontal-degree "
            "drill lights the orbit with transpose-next overlays (no modulation claim)."),
        node_classes=node_classes, edge_classes=edge_classes, layout_rules=layout_rules,
        generation_rules=["transposition_orbit_edges"],
        node_generation_rules=["transposition_orbit_nodes"],
        layout_strategy="key_local",
        context_schema={"degree": "V", "mode": "major", "keys": []},
        center_keys=["C"],
        node_layers=["degree_class", "diatonic_triad"],
        launch_rules={"launchable_kinds": ["diatonic_triad", "degree_class"],
                      "reserved_kinds": [], "reserved_reason": ""},
    )


def quality_class_network_v1() -> HarmonicNetworkTemplate:
    """A key's diatonic triads grouped by chord quality (major / minor / diminished).

    Quality-class nodes anchor the exact diatonic triads of the active key that share each
    quality.  The overlay is ``enumerate_next`` (a classification, never a progression, plan
    section 14.4).
    """
    node_classes = [
        NodeClass("quality_class", "Quality class", "purple", "#a855f7",
                  "A chord-quality category (major / minor / diminished / augmented).",
                  semantic_level="class", entity_role="reference", canonical_ref="quality"),
        NodeClass("diatonic_triad", "Diatonic triad", "teal", "#14b8a6",
                  "An exact diatonic triad of the key, classified by its quality.",
                  semantic_level="chord", entity_role="instance", canonical_ref="triad"),
    ]
    edge_classes = [
        EdgeClass("instance_of", "Instance of", directed=True,
                  visual_class="membership", default_visible=True,
                  description="A triad is an instance of its quality class."),
    ]
    layout_rules = [
        LayoutRule("quality_class", "inner", radius=140.0, angle_offset=0.0, node_radius=24.0),
        LayoutRule("diatonic_triad", "outer", radius=300.0, angle_offset=0.0, node_radius=19.0),
    ]
    return HarmonicNetworkTemplate(
        template_id="quality_class_network_v1",
        title="Quality-class network",
        description=(
            "The seven diatonic triads of the active key grouped by chord quality. A quality "
            "drill enumerates a class's members; the overlay is a classification, not a "
            "progression."),
        node_classes=node_classes, edge_classes=edge_classes, layout_rules=layout_rules,
        generation_rules=["quality_membership_edges"],
        node_generation_rules=["quality_class_nodes"],
        layout_strategy="key_local",
        context_schema={"key": "C", "mode": "major"},
        center_keys=["C"],
        node_layers=["quality_class", "diatonic_triad"],
        launch_rules={"launchable_kinds": ["diatonic_triad", "quality_class"],
                      "reserved_kinds": [], "reserved_reason": ""},
    )


def functional_equivalence_network_v1() -> HarmonicNetworkTemplate:
    """The dominant-function alternatives (V triad / V7 / vii°) sharing one function.

    Shows the exact distinction between the launchable V triad, the *reserved* dominant seventh
    (the engine is triad-based), and the leading-tone diminished triad -- all members of, or
    substitutes within, the dominant function (plan section 14.4).
    """
    node_classes = [
        NodeClass("function_family", "Dominant function", "amber", "#f59e0b",
                  "The dominant function the alternatives share.",
                  semantic_level="function", entity_role="family", canonical_ref="function"),
        NodeClass("diatonic_triad", "V triad", "teal", "#14b8a6",
                  "The V major triad (launchable).",
                  semantic_level="chord", entity_role="instance", canonical_ref="triad"),
        NodeClass("dominant_seventh", "V7 (reserved)", "yellow", "#facc15",
                  "The dominant seventh -- a reserved node (the engine is triad-based).",
                  semantic_level="chord", entity_role="reference", canonical_ref="triad"),
        NodeClass("diminished_triad", "vii°", "purple", "#a855f7",
                  "The leading-tone diminished triad (a rootless dominant; launchable).",
                  semantic_level="chord", entity_role="instance", canonical_ref="triad"),
    ]
    edge_classes = [
        EdgeClass("member_of_function", "Member of function", directed=True,
                  visual_class="membership", default_visible=True,
                  description="A chord is a member of the dominant function."),
        EdgeClass("substitutes_for", "Substitutes for", directed=True,
                  visual_class="substitute", default_visible=True,
                  description="The V7 substitutes for (extends) the V triad."),
        EdgeClass("same_function", "Same function", directed=False,
                  visual_class="function", default_visible=True,
                  description="V7 and vii° share the dominant function."),
    ]
    layout_rules = [
        LayoutRule("function_family", "central", radius=0.0, angle_offset=0.0, node_radius=26.0),
        LayoutRule("diatonic_triad", "outer", radius=210.0, angle_offset=0.0, node_radius=20.0),
        LayoutRule("dominant_seventh", "outer", radius=210.0, angle_offset=120.0, node_radius=20.0),
        LayoutRule("diminished_triad", "outer", radius=210.0, angle_offset=240.0, node_radius=20.0),
    ]
    return HarmonicNetworkTemplate(
        template_id="functional_equivalence_network_v1",
        title="Functional-equivalence network",
        description=(
            "The dominant-function alternatives V, V7 and vii° with the exact distinction "
            "between triad, seventh chord and diminished triad. The V7 stays reserved until "
            "seventh-chord support expands; the V triad and vii° are launchable."),
        node_classes=node_classes, edge_classes=edge_classes, layout_rules=layout_rules,
        generation_rules=["functional_equivalence_edges"],
        node_generation_rules=["functional_equivalence_nodes"],
        layout_strategy="key_local",
        context_schema={"key": "C", "mode": "major"},
        center_keys=["C"],
        node_layers=["function_family", "diatonic_triad", "dominant_seventh", "diminished_triad"],
        launch_rules={
            "launchable_kinds": ["diatonic_triad", "diminished_triad", "function_family"],
            "reserved_kinds": ["dominant_seventh"],
            "reserved_reason": ("The engine is triad-based; seventh-chord drills are reserved. "
                                "The V triad and vii° are launchable."),
        },
    )


# ---------------------------------------------------------------------------
# Template registry (future topologies register here)
# ---------------------------------------------------------------------------

TEMPLATES = {
    "dominant_diminished_relative_network_v1":
        dominant_diminished_relative_network_v1,
    "core_triad_function_network_v1":
        core_triad_function_network_v1,
    "cadence_resolution_network_v1":
        cadence_resolution_network_v1,
    "inversion_space_network_v1":
        inversion_space_network_v1,
    "transposition_orbit_network_v1":
        transposition_orbit_network_v1,
    "quality_class_network_v1":
        quality_class_network_v1,
    "functional_equivalence_network_v1":
        functional_equivalence_network_v1,
}

DEFAULT_TEMPLATE_ID = "dominant_diminished_relative_network_v1"


def get_template(template_id: Optional[str] = None) -> HarmonicNetworkTemplate:
    """Return a validated template by id (default: the v1 reference template)."""
    tid = template_id or DEFAULT_TEMPLATE_ID
    if tid not in TEMPLATES:
        raise KeyError(
            f"unknown template {tid!r}; available: {sorted(TEMPLATES)}")
    tpl = TEMPLATES[tid]()
    tpl.validate()
    return tpl


def load_template(data: Dict) -> HarmonicNetworkTemplate:
    """Load (and validate) a template from a serialised dict (future loading)."""
    return HarmonicNetworkTemplate.from_dict(data)


# ---------------------------------------------------------------------------
# Planned (not-yet-built) templates -- metadata stubs only
# ---------------------------------------------------------------------------
#
# These are *audited* future topologies (see docs/harmonic_network_template_audit.md).
# They are intentionally metadata-only: no generation rules, no factory, and NOT
# registered in ``TEMPLATES``, so ``get_template()`` keeps working for the one
# buildable template.  A stub graduates to a real template by writing a builder
# + factory and moving it into ``TEMPLATES``.

@dataclass(frozen=True)
class PlannedTemplate:
    """A reserved future network template -- description + rationale only."""

    template_id: str
    title: str
    description: str
    rationale: str
    status: str = "planned"
    priority: str = "medium"            # low | medium | high
    dependencies: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict:
        return asdict(self)


PLANNED_TEMPLATES: List[PlannedTemplate] = [
    PlannedTemplate(
        template_id="modulation_path_network_v1",
        title="Modulation-path network",
        description=(
            "Movement between key areas via pivot / common chords, distinct from a mere "
            "transposition. Reserved until pivot-chord / chromatic support exists."),
        rationale=(
            "The `modulation_path` thematic group is explicitly reserved (plan section 3.1): "
            "a real modulation must not be inferred from adjacent key changes. Needs pivot-chord "
            "detection the engine does not yet have."),
        priority="low",
        dependencies=["pivot-chord / chromatic support (a non-goal for now)",
                      "the reserved modulation_path_to relation"],
    ),
    PlannedTemplate(
        template_id="secondary_dominant_network_v1",
        title="Secondary-dominant network",
        description=(
            "Applied dominants (V/V, V/ii, ...) and their tonicisation targets, using the "
            "reserved secondary_dominant_of relation."),
        rationale=(
            "Secondary dominants are an explicit non-goal until the trainer grows chromatic / "
            "seventh-chord support; the relation is reserved so the honesty model stays intact."),
        priority="low",
        dependencies=["chromatic / seventh-chord trainer support (a non-goal for now)",
                      "the reserved secondary_dominant_of relation"],
    ),
]


def list_planned_templates() -> List[Dict]:
    """Metadata for every planned (not-yet-built) template."""
    return [pt.to_dict() for pt in PLANNED_TEMPLATES]


def list_templates() -> List[Dict]:
    """Every template: the buildable one(s) (``status='implemented'``) + planned stubs."""
    out: List[Dict] = []
    for tid, factory in TEMPLATES.items():
        tpl = factory()
        out.append({
            "template_id": tid,
            "title": tpl.title,
            "description": tpl.description,
            "status": "implemented",
            "priority": "shipped",
            "rationale": "",
            "dependencies": [],
        })
    out.extend(list_planned_templates())
    return out
