"""Topological templates for the Harmonic Network / Tonal Graph layer.

The **Harmonic Network** is a *relational* layer on top of the existing
pedagogical map (Circle of Fifths → Interactive Harmony Atlas → Music Theory
Laboratory / Curriculum).  Where the Atlas answers "what is the invariant degree
pattern, and how does it transpose", the Network answers "how are *whole keys,
relative minors, dominant sevenths and leading-tone diminished triads* wired
together by fifths, relative relations and functional pull".

This module is the **schema** for that layer.  A
:class:`HarmonicNetworkTemplate` is a pure, serialisable description of:

* the node *classes* (major key / minor key / dominant seventh / diminished),
  each with a visual class (the reference image's pink / blue / yellow / purple);
* the edge *classes* (the relationship vocabulary), split into implemented and
  reserved relations;
* the layout rules (concentric rings + angular placement by fifth index);
* which deterministic *generation rules* the builder should run;
* the launch rules (what is launchable vs. reserved).

It deliberately contains **no theory tables**: the actual nodes/edges are
generated by :mod:`harmony.harmonic_network` from the live theory engine
(:mod:`theory.diatonic_harmony`) so the network can never drift from the rest of
the app.  The first concrete template,
``dominant_diminished_relative_network_v1``, reconstructs the topology of the
Brian-Callipari-style reference image (``images/571334612_*.jpg``) as a *formal
music-theory graph*, not an image trace.

Later topologies are added by writing another :class:`HarmonicNetworkTemplate`
with the same schema and registering it in :data:`TEMPLATES`.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional


SCHEMA_VERSION = "harmony-network-template/v1"

# ---------------------------------------------------------------------------
# Controlled vocabularies (the schema's closed sets)
# ---------------------------------------------------------------------------

#: The four node classes the first template uses.  A template may use a subset.
NODE_KINDS = [
    "major_key",
    "minor_key",
    "dominant_seventh",
    "diminished_triad",
]

#: Relationship vocabulary that is *implemented* by the v1 graph builder.
IMPLEMENTED_RELATIONS = [
    "fifth_relation",
    "relative_minor_of",
    "relative_major_of",
    "dominant_of",
    "resolves_to",
    "leading_tone_to",
    "shares_scale_with",
    "same_pitch_class",
    "same_function",
    "trainer_drill_available",
    "atlas_node_available",
]

#: Relationship vocabulary that is *reserved* (named now, generated later).
RESERVED_RELATIONS = [
    "secondary_dominant_of",
    "borrowed_from_parallel",
    "tritone_substitute_of",
    "common_tone_diminished",
    "enharmonic_equivalent_of",
    "modulation_path_to",
]

#: Every relation a template may legally name (implemented + reserved).
ALL_RELATIONS = IMPLEMENTED_RELATIONS + RESERVED_RELATIONS

#: The deterministic edge-generation passes the builder knows how to run.
GENERATION_RULES = [
    "major_circle_by_fifths",       # 1. major keys connect by fifths/fourths
    "relative_minor_edges",         # 2. C major <-> A minor, ...
    "dominant_seventh_resolution_edges",  # 3. G7 -> C, D7 -> G, ...
    "leading_tone_diminished_edges",      # 4. B° -> C, F#° -> G, ...
    "shared_scale_edges",           # 5. shared-scale relations (optional layer)
    "same_function_edges",          # V7 and vii° share the dominant function
    "same_pitch_class_edges",       # cross-class same-root overlay (optional)
    "integration_overlays",         # trainer_drill_available / atlas_node_available
]

#: The visual classes (colours) from the reference image.
VISUAL_CLASSES = ["pink", "blue", "yellow", "purple"]


# ---------------------------------------------------------------------------
# Schema dataclasses
# ---------------------------------------------------------------------------

@dataclass
class NodeClass:
    """One node class: a kind + how it is drawn + what it means."""

    kind: str
    label: str
    visual_class: str            # pink | blue | yellow | purple
    color: str                   # hex fill
    description: str = ""

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class EdgeClass:
    """One relationship type in the network's vocabulary."""

    relation: str
    label: str
    directed: bool = True
    implemented: bool = True     # False => reserved (no edges generated yet)
    visual_class: str = "default"
    default_visible: bool = True
    description: str = ""

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class LayoutRule:
    """Where a node class sits: a concentric ring + per-spoke offsets."""

    kind: str
    ring: str                    # outer | inner | dominant | central (label only)
    radius: float                # distance from centre
    angle_offset: float = 0.0    # degrees added to the spoke angle (fifth index)
    node_radius: float = 18.0    # drawn circle radius

    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class HarmonicNetworkTemplate:
    """A serialisable topological template (the schema of one network)."""

    template_id: str
    title: str
    description: str
    node_classes: List[NodeClass]
    edge_classes: List[EdgeClass]
    layout_rules: List[LayoutRule]
    generation_rules: List[str]
    #: The 12 circle-of-fifths *major* tonics, clockwise from the top, spelled
    #: the way the template wants them displayed (this is *layout data*, not a
    #: theory table -- every chord is still derived from the engine).
    center_keys: List[str] = field(default_factory=list)
    node_layers: List[str] = field(default_factory=list)
    launch_rules: Dict[str, Any] = field(default_factory=dict)
    schema: str = SCHEMA_VERSION

    # -- lookups ---------------------------------------------------------
    def node_class(self, kind: str) -> NodeClass:
        for nc in self.node_classes:
            if nc.kind == kind:
                return nc
        raise KeyError(f"no node class for kind {kind!r}")

    def edge_class(self, relation: str) -> EdgeClass:
        for ec in self.edge_classes:
            if ec.relation == relation:
                return ec
        raise KeyError(f"no edge class for relation {relation!r}")

    def layout_for(self, kind: str) -> LayoutRule:
        for lr in self.layout_rules:
            if lr.kind == kind:
                return lr
        raise KeyError(f"no layout rule for kind {kind!r}")

    def kinds(self) -> List[str]:
        return [nc.kind for nc in self.node_classes]

    def relations(self) -> List[str]:
        return [ec.relation for ec in self.edge_classes]

    def implemented_relations(self) -> List[str]:
        return [ec.relation for ec in self.edge_classes if ec.implemented]

    # -- validation ------------------------------------------------------
    def validate(self) -> None:
        """Raise :class:`ValueError` on any malformed / unknown-vocabulary field.

        Checks (the schema's contract):
          * required scalar fields are present and non-empty;
          * every node class names a known kind (``NODE_KINDS``);
          * every edge class names a known relation (implemented or reserved);
          * every generation rule is recognised;
          * every node class has exactly one layout rule and vice-versa;
          * visual classes are from the known palette.
        """
        if not self.template_id:
            raise ValueError("template requires a non-empty template_id")
        if not self.title:
            raise ValueError("template requires a non-empty title")
        if not self.node_classes:
            raise ValueError("template requires at least one node class")
        if not self.edge_classes:
            raise ValueError("template requires at least one edge class")
        if not self.layout_rules:
            raise ValueError("template requires layout rules")

        seen_kinds = set()
        for nc in self.node_classes:
            if nc.kind not in NODE_KINDS:
                raise ValueError(
                    f"unknown node class {nc.kind!r}; expected one of {NODE_KINDS}")
            if nc.kind in seen_kinds:
                raise ValueError(f"duplicate node class {nc.kind!r}")
            seen_kinds.add(nc.kind)
            if nc.visual_class not in VISUAL_CLASSES:
                raise ValueError(
                    f"unknown visual class {nc.visual_class!r} for {nc.kind!r}; "
                    f"expected one of {VISUAL_CLASSES}")

        for ec in self.edge_classes:
            if ec.relation not in ALL_RELATIONS:
                raise ValueError(
                    f"unknown edge relation {ec.relation!r}; expected one of "
                    f"{ALL_RELATIONS}")
            # A reserved relation must not advertise itself as implemented.
            if ec.relation in RESERVED_RELATIONS and ec.implemented:
                raise ValueError(
                    f"relation {ec.relation!r} is reserved and cannot be marked "
                    f"implemented")

        for rule in self.generation_rules:
            if rule not in GENERATION_RULES:
                raise ValueError(
                    f"unknown generation rule {rule!r}; expected one of "
                    f"{GENERATION_RULES}")

        layout_kinds = set()
        for lr in self.layout_rules:
            if lr.kind not in seen_kinds:
                raise ValueError(
                    f"layout rule for {lr.kind!r} has no matching node class")
            layout_kinds.add(lr.kind)
        missing = seen_kinds - layout_kinds
        if missing:
            raise ValueError(f"node classes missing a layout rule: {sorted(missing)}")

    # -- serialisation ---------------------------------------------------
    def to_dict(self) -> Dict:
        return {
            "schema": self.schema,
            "template_id": self.template_id,
            "title": self.title,
            "description": self.description,
            "node_layers": list(self.node_layers),
            "node_classes": [nc.to_dict() for nc in self.node_classes],
            "edge_classes": [ec.to_dict() for ec in self.edge_classes],
            "layout_rules": [lr.to_dict() for lr in self.layout_rules],
            "generation_rules": list(self.generation_rules),
            "center_keys": list(self.center_keys),
            "launch_rules": dict(self.launch_rules),
        }

    @classmethod
    def from_dict(cls, d: Dict) -> "HarmonicNetworkTemplate":
        tpl = cls(
            template_id=d["template_id"],
            title=d["title"],
            description=d.get("description", ""),
            node_classes=[NodeClass(**nc) for nc in d.get("node_classes", [])],
            edge_classes=[EdgeClass(**ec) for ec in d.get("edge_classes", [])],
            layout_rules=[LayoutRule(**lr) for lr in d.get("layout_rules", [])],
            generation_rules=list(d.get("generation_rules", [])),
            center_keys=list(d.get("center_keys", [])),
            node_layers=list(d.get("node_layers", [])),
            launch_rules=dict(d.get("launch_rules", {})),
            schema=d.get("schema", SCHEMA_VERSION),
        )
        tpl.validate()
        return tpl


# ---------------------------------------------------------------------------
# The first concrete template
# ---------------------------------------------------------------------------

#: 12 major tonics, clockwise from C at 12 o'clock, spelled to match the
#: reference image (sharps on the top half, flats on the bottom half, F# at the
#: 6-o'clock enharmonic seam).  Purely the *display order*; every relative
#: minor / dominant seventh / diminished triad is derived from the engine.
CIRCLE_OF_FIFTHS_MAJOR = [
    "C", "G", "D", "A", "E", "B", "F#", "Db", "Ab", "Eb", "Bb", "F",
]


def dominant_diminished_relative_network_v1() -> HarmonicNetworkTemplate:
    """Reconstruct the reference image's topology as a formal theory graph.

    Four concentric rings around a central crosshair:
      * **major keys** (pink) and their **relative minors** (blue) alternate on
        the outer ring, ordered by the circle of fifths;
      * each key's **dominant seventh** (yellow) sits on the same radial spoke,
        midway in;
      * each key's **leading-tone diminished triad** (purple) sits innermost.

    Arrows show functional pull: V7 → I and vii° → I (to both the major tonic
    and the same-pitch-class minor tonic across the field), giving the
    characteristic crossing resolution arcs of the reference image.
    """
    node_classes = [
        NodeClass("major_key", "Major key", "pink", "#ec4899",
                  "A major key (tonic). Outer ring, ordered by the circle of "
                  "fifths."),
        NodeClass("minor_key", "Relative minor", "blue", "#38bdf8",
                  "The relative minor of a major key (shares its key signature)."),
        NodeClass("dominant_seventh", "Dominant seventh", "yellow", "#facc15",
                  "The V7 of a key. A theoretical node: seventh-chord drills are "
                  "reserved (the engine is triad-based)."),
        NodeClass("diminished_triad", "Leading-tone diminished", "purple",
                  "#a855f7",
                  "The vii° (leading-tone) diminished triad of a key; a rootless "
                  "dominant that resolves to the tonic."),
    ]

    edge_classes = [
        EdgeClass("fifth_relation", "Fifth relation", directed=True,
                  visual_class="fifth", default_visible=True,
                  description="Adjacent major keys a perfect fifth apart."),
        EdgeClass("relative_minor_of", "Relative minor of", directed=False,
                  visual_class="relative", default_visible=True,
                  description="Major key → its relative minor."),
        EdgeClass("relative_major_of", "Relative major of", directed=False,
                  visual_class="relative", default_visible=True,
                  description="Relative minor → its relative major."),
        EdgeClass("dominant_of", "Dominant of", directed=True,
                  visual_class="dominant", default_visible=False,
                  description="A dominant seventh is the V7 of its tonic "
                              "(functional label twin of resolves_to)."),
        EdgeClass("resolves_to", "Resolves to", directed=True,
                  visual_class="resolve", default_visible=True,
                  description="Functional resolution (V7 → I, vii° → I)."),
        EdgeClass("leading_tone_to", "Leading-tone to", directed=True,
                  visual_class="leading", default_visible=True,
                  description="A diminished triad's leading tone resolves up to "
                              "the tonic."),
        EdgeClass("shares_scale_with", "Shares scale with", directed=False,
                  visual_class="shared", default_visible=False,
                  description="Diatonically related keys (relative + ii/iii/vi "
                              "minors). Optional layer to avoid clutter."),
        EdgeClass("same_pitch_class", "Same pitch class", directed=False,
                  visual_class="samepc", default_visible=False,
                  description="Nodes whose root is the same pitch class "
                              "(cross-class overlay)."),
        EdgeClass("same_function", "Same function", directed=False,
                  visual_class="function", default_visible=True,
                  description="V7 and vii° of a key share the dominant function "
                              "(vii° is a rootless V7)."),
        EdgeClass("trainer_drill_available", "Trainer drill available",
                  directed=True, visual_class="trainer", default_visible=False,
                  description="Points at the closest launchable Harmony Trainer "
                              "triad drill for this node."),
        EdgeClass("atlas_node_available", "Atlas node available", directed=True,
                  visual_class="atlas", default_visible=False,
                  description="Points at the related Interactive Harmony Atlas "
                              "concept node."),
        # Reserved vocabulary -- named now, generated by a future layer.
        EdgeClass("secondary_dominant_of", "Secondary dominant of", directed=True,
                  implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
        EdgeClass("borrowed_from_parallel", "Borrowed from parallel",
                  directed=True, implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
        EdgeClass("tritone_substitute_of", "Tritone substitute of", directed=True,
                  implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
        EdgeClass("common_tone_diminished", "Common-tone diminished",
                  directed=True, implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
        EdgeClass("enharmonic_equivalent_of", "Enharmonic equivalent of",
                  directed=False, implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
        EdgeClass("modulation_path_to", "Modulation path to", directed=True,
                  implemented=False, visual_class="reserved",
                  default_visible=False, description="Reserved."),
    ]

    layout_rules = [
        LayoutRule("major_key", "outer", radius=300.0, angle_offset=0.0,
                   node_radius=21.0),
        LayoutRule("minor_key", "outer", radius=300.0, angle_offset=15.0,
                   node_radius=19.0),
        LayoutRule("dominant_seventh", "dominant", radius=192.0, angle_offset=0.0,
                   node_radius=18.0),
        LayoutRule("diminished_triad", "central", radius=112.0, angle_offset=0.0,
                   node_radius=17.0),
    ]

    return HarmonicNetworkTemplate(
        template_id="dominant_diminished_relative_network_v1",
        title="Dominant / diminished / relative-minor harmonic network",
        description=(
            "A topological reconstruction of the Brian-Callipari-style harmonic "
            "network: the 12 major keys and their relative minors on the outer "
            "ring (circle of fifths), each key's dominant seventh midway in, and "
            "each key's leading-tone diminished triad innermost. Resolution "
            "arrows (V7 → I, vii° → I) wire the field together. Reconstructed "
            "deterministically from the theory engine, not traced from the image."),
        node_classes=node_classes,
        edge_classes=edge_classes,
        layout_rules=layout_rules,
        generation_rules=[
            "major_circle_by_fifths",
            "relative_minor_edges",
            "dominant_seventh_resolution_edges",
            "leading_tone_diminished_edges",
            "same_function_edges",
            "shared_scale_edges",
            "same_pitch_class_edges",
            "integration_overlays",
        ],
        center_keys=list(CIRCLE_OF_FIFTHS_MAJOR),
        node_layers=["major_key", "minor_key", "dominant_seventh",
                     "diminished_triad"],
        launch_rules={
            # Triad-based drills are launchable; seventh-chord drills are reserved
            # until the engine grows seventh chords.
            "launchable_kinds": ["major_key", "minor_key", "diminished_triad"],
            "reserved_kinds": ["dominant_seventh"],
            "reserved_reason": (
                "The theory engine is triad-based; seventh-chord exercises are "
                "not implemented. Dominant-seventh nodes link to the closest "
                "available triad drill (the V→I resolution) instead."),
        },
    )


# ---------------------------------------------------------------------------
# Template registry (future topologies register here)
# ---------------------------------------------------------------------------

TEMPLATES = {
    "dominant_diminished_relative_network_v1":
        dominant_diminished_relative_network_v1,
}

DEFAULT_TEMPLATE_ID = "dominant_diminished_relative_network_v1"


def get_template(template_id: Optional[str] = None) -> HarmonicNetworkTemplate:
    """Return a validated template by id (default: the v1 reference template)."""
    tid = template_id or DEFAULT_TEMPLATE_ID
    if tid not in TEMPLATES:
        raise KeyError(
            f"unknown template {tid!r}; available: {sorted(TEMPLATES)}")
    tpl = TEMPLATES[tid]()
    tpl.validate()
    return tpl


def load_template(data: Dict) -> HarmonicNetworkTemplate:
    """Load (and validate) a template from a serialised dict (future loading)."""
    return HarmonicNetworkTemplate.from_dict(data)
